sonar.exclusions=**/assets/**,**/tests/**,**/docs/**,**/example/**,**/tools/**,**/benchmarks/**

sonar.coverage.exclusions=**/tests/**,**/example/**

sonar.tests=tests
sonar.test.inclusions=**/*Tests.cs
sonar.test.inclusions=**/*Test.cs
