sonar.sources=src

sonar.tests=tests
sonar.test.inclusions=**/*Test.cs,**/*Tests.cs

sonar.exclusions=**/assets/**,**/docs/**,**/example/**,**/tools/**,**/benchmarks/**
sonar.coverage.exclusions=**/example/**

# Optional
sonar.cs.vstest.reportsPaths=**/TestResults/*.trx
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
