sonar.sources=src

sonar.tests=tests
sonar.test.inclusions=**/*Test.cs,**/*Tests.cs

sonar.exclusions=**/assets/**,**/docs/**,**/example/**,**/tools/**,**/benchmarks/**
sonar.coverage.exclusions=**/example/**

# Optional
sonar.cs.vstest.reportsPaths=**/TestResults/*.trx
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml

sonar.issue.ignore.multicriteria=e1,e2

# Ignore tất cả rule trong benchmarks/**
sonar.issue.ignore.multicriteria.e1.resourceKey=**/benchmarks/**
sonar.issue.ignore.multicriteria.e1.ruleKey=*

# Ignore tất cả rule trong tests/**
sonar.issue.ignore.multicriteria.e2.resourceKey=**/tests/**
sonar.issue.ignore.multicriteria.e2.ruleKey=*
