// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Nalix.Abstractions.Networking.Packets;
using Nalix.Abstractions.Networking.Protocols;
using Nalix.Abstractions.Primitives;
using Nalix.Abstractions.Serialization;
using Nalix.Codec.DataFrames;

namespace Nalix.Codec.ProtocolFrames;

/// <summary>
/// Represents a challenge issued by the server to the client.
/// </summary>
[Packet]
[GenerateFormatter]
[ExcludeFromCodeCoverage]
[SerializePackable(SerializeLayout.Explicit)]
[DebuggerDisplay("POW_CHALLENGE Diff={Difficulty}")]
public sealed partial class ProofOfWorkChallenge : PacketBase<ProofOfWorkChallenge>, IFixedSizeSerializable, IPacketValidatable, IPacketStaticOpcode
{
    /// <inheritdoc/>
    public static ushort StaticOpCode => (ushort)ProtocolOpCode.POW_CHALLENGE;

    /// <summary>
    /// Random bytes generated by the server.
    /// </summary>
    [SerializeOrder(0)]
    public Bytes32 Nonce { get; set; }

    /// <summary>
    /// The required number of leading zero bits.
    /// </summary>
    [SerializeOrder(1)]
    public byte Difficulty { get; set; }

    /// <summary>
    /// The timestamp when the challenge was generated.
    /// </summary>
    [SerializeOrder(2)]
    public long TimestampTicks { get; set; }

    /// <summary>
    /// Message Authentication Code to ensure the challenge is not forged.
    /// </summary>
    [SerializeOrder(3)]
    public Bytes32 Mac { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="ProofOfWorkChallenge"/> class.
    /// </summary>
    public ProofOfWorkChallenge() => this.ResetForPool();

    /// <summary>
    /// Initializes the packet with the specified challenge parameters.
    /// </summary>
    public void Initialize(Bytes32 nonce, byte diff, long ts, Bytes32 mac, PacketFlags flags = PacketFlags.SYSTEM)
    {
        this.Priority = PacketPriority.URGENT;
        this.Flags = flags;
        this.Nonce = nonce;
        this.Difficulty = diff;
        this.TimestampTicks = ts;
        this.Mac = mac;
    }

    /// <inheritdoc/>
    public override void ResetForPool()
    {
        base.ResetForPool();
        this.Nonce = Bytes32.Zero;
        this.Difficulty = 0;
        this.TimestampTicks = 0;
        this.Mac = Bytes32.Zero;
        this.Priority = PacketPriority.URGENT;
        this.Flags = PacketFlags.SYSTEM;
    }

    /// <inheritdoc/>
    public bool Validate([NotNullWhen(false)] out string? failureReason)
    {
        if (this.Nonce.IsZero || this.Mac.IsZero || this.TimestampTicks <= 0)
        {
            failureReason = "Invalid PowChallenge data.";
            return false;
        }
        failureReason = null;
        return true;
    }
}
