// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Nalix.AutoGenerated;

/// <summary>
/// Generates packet registration and fast-dispatch code for packets marked with PacketAttribute.
/// </summary>
[Generator]
public sealed class PacketRegistryGenerator : IIncrementalGenerator
{
    #region Constants and Diagnostics

    private const string PacketBaseName = "PacketBase";
    private const string PacketBaseNamespace = "Nalix.Codec.DataFrames";
    private const string PacketAttributeMetadataName = "Nalix.Abstractions.Networking.Packets.PacketAttribute";

    private const int MaxTableSize = 4096;

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("MicrosoftCodeAnalysisReleaseTracking", "RS2008:Enable analyzer release tracking", Justification = "<Pending>")]
    private static readonly DiagnosticDescriptor HashCollisionError = new(
        id: "NALIX059",
        title: "Packet hash table collision limit exceeded",
        messageFormat: "Cannot find a collision-free dispatch table for {0} packet(s). Maximum table size ({1}) reached. Consider reducing packet count or changing the hash function.",
        category: "PacketRegistry",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    #endregion Constants and Diagnostics

    #region IIncrementalGenerator Implementation

    /// <summary>
    /// Registers the incremental source-generation pipeline.
    /// </summary>
    /// <param name="context">The Roslyn incremental generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol?> packets = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax { AttributeLists.Count: > 0, BaseList: not null },
                transform: static (ctx, _) => GET_PACKET_TYPE(ctx))
            .Where(static symbol => symbol is not null);

        IncrementalValueProvider<System.Collections.Immutable.ImmutableArray<INamedTypeSymbol?>> collected = packets.Collect();

        context.RegisterSourceOutput(collected, static (spc, source) => EXECUTE(source, spc));
    }

    #endregion IIncrementalGenerator Implementation

    #region Private Helpers

    private static INamedTypeSymbol? GET_PACKET_TYPE(GeneratorSyntaxContext context)
    {
        if (context.Node is not TypeDeclarationSyntax typeDecl)
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(typeDecl) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.IsAbstract || symbol.TypeKind == TypeKind.Interface || symbol.IsGenericType)
        {
            return null;
        }

        if (!HAS_PACKET_ATTRIBUTE(symbol))
        {
            return null;
        }

        return INHERITS_PACKET_BASE_OF_SELF(symbol) ? symbol : null;
    }

    private static bool HAS_PACKET_ATTRIBUTE(INamedTypeSymbol symbol) =>
        symbol.GetAttributes().Any(static attr => attr.AttributeClass?.ToDisplayString() == PacketAttributeMetadataName);

    private static bool INHERITS_PACKET_BASE_OF_SELF(INamedTypeSymbol symbol)
    {
        INamedTypeSymbol? current = symbol.BaseType;
        while (current is not null)
        {
            if (current.Name == PacketBaseName &&
                current.ContainingNamespace.ToDisplayString() == PacketBaseNamespace &&
                current.TypeArguments.Length == 1 &&
                SymbolEqualityComparer.Default.Equals(current.TypeArguments[0], symbol))
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }

    private static void EXECUTE(
        System.Collections.Immutable.ImmutableArray<INamedTypeSymbol?> packets,
        SourceProductionContext context)
    {
        HashSet<string> seen = new();
        List<INamedTypeSymbol> distinctPackets = [.. packets
            .Where(static p => p is not null)
            .Select(static p => p!)
            .Where(p => seen.Add(p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
            .OrderBy(static p => p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))];

        if (distinctPackets.Count == 0)
        {
            return;
        }

        EMIT_BOOTSTRAP(distinctPackets, context);
    }

    private static int FIND_TABLE_SIZE(IReadOnlyList<INamedTypeSymbol> packets)
    {
        int tableSize = 1;
        while (tableSize <= MaxTableSize)
        {
            tableSize <<= 1;
            HashSet<int> slots = new();
            bool collision = false;

            foreach (INamedTypeSymbol packet in packets)
            {
                string fullName = packet.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
                uint key = COMPUTE(fullName);
                if (!slots.Add((int)(key & (uint)(tableSize - 1))))
                {
                    collision = true;
                    break;
                }
            }

            if (!collision)
            {
                return tableSize;
            }
        }

        return -1;
    }

    private static void EMIT_BOOTSTRAP(IReadOnlyList<INamedTypeSymbol> packets, SourceProductionContext context)
    {
        int tableSize = FIND_TABLE_SIZE(packets);
        if (tableSize < 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                HashCollisionError,
                Location.None,
                packets.Count,
                MaxTableSize));
            return;
        }

        uint mask = (uint)(tableSize - 1);

        (uint Key, string TypeName, bool Used)[] entries = new (uint Key, string TypeName, bool Used)[tableSize];

        foreach (INamedTypeSymbol packet in packets)
        {
            string typeName = packet.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string fullName = packet.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
            uint key = COMPUTE(fullName);
            int slot = (int)(key & mask);
            entries[slot] = (key, typeName, true);
        }

        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#pragma warning disable CS1591");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine("using System.Runtime.CompilerServices;");
        _ = sb.AppendLine("using System.Threading;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("namespace Nalix.AutoGenerated;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("internal static class PacketBootstrap");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    private static int s_registered;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    [ModuleInitializer]");
        _ = sb.AppendLine("    internal static void Initialize() => Register();");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    internal static void Register()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (Interlocked.Exchange(ref s_registered, 1) != 0)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();

        foreach (INamedTypeSymbol packet in packets)
        {
            string typeName = packet.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string fullName = packet.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
            uint key = COMPUTE(fullName);
            _ = sb.AppendLine($"        global::Nalix.Codec.DataFrames.PacketRegistry.RegisterGenerated(");
            _ = sb.AppendLine($"            {key.ToString(System.Globalization.CultureInfo.InvariantCulture)}u,");
            _ = sb.AppendLine($"            \"{ESCAPE(fullName)}\",");
            _ = sb.AppendLine($"            static raw => {typeName}.Deserialize(raw));");
            _ = sb.AppendLine();
        }

        _ = sb.AppendLine("        global::Nalix.Codec.DataFrames.PacketRegistry.RegisterGenerated(s_dispatcher);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private readonly struct PacketEntry");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        internal readonly uint Key;");
        _ = sb.AppendLine("        internal readonly PacketDeserializer? Fn;");
        _ = sb.AppendLine("        internal PacketEntry(uint key, PacketDeserializer fn) { Key = key; Fn = fn; }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private delegate global::Nalix.Abstractions.Networking.Packets.IPacket PacketDeserializer(global::System.ReadOnlySpan<byte> raw);");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"    private const uint Mask = {mask}u;");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private static readonly global::Nalix.Codec.DataFrames.PacketFastDispatcher s_dispatcher = TryDeserialize;");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private static readonly PacketEntry[] Table = [");
        for (int i = 0; i < tableSize; i++)
        {
            (uint key, string typeName, bool used) = entries[i];
            if (used)
            {
                string keyLiteral = key.ToString(System.Globalization.CultureInfo.InvariantCulture);
                _ = sb.AppendLine($"        new({keyLiteral}u, static raw => {typeName}.Deserialize(raw)),");
            }
            else
            {
                _ = sb.AppendLine("        default,");
            }
        }
        _ = sb.AppendLine("    ];");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]");
        _ = sb.AppendLine("    private static global::Nalix.Abstractions.Networking.Packets.IPacket? Resolve(uint magic, global::System.ReadOnlySpan<byte> raw)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        PacketEntry entry = Table[(int)(magic & Mask)];");
        _ = sb.AppendLine("        return entry.Fn is not null && entry.Key == magic ? entry.Fn(raw) : null;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]");
        _ = sb.AppendLine("    private static bool TryDeserialize(uint magic, global::System.ReadOnlySpan<byte> raw, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::Nalix.Abstractions.Networking.Packets.IPacket? packet)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        packet = Resolve(magic, raw);");
        _ = sb.AppendLine("        return packet is not null;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        context.AddSource("PacketBootstrap.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static uint COMPUTE(string name)
    {
        const uint offset = 2166136261u;
        const uint prime = 16777619u;

        uint hash = offset;
        foreach (char ch in name)
        {
            hash ^= ch;
            hash *= prime;
        }

        return hash;
    }

    private static string ESCAPE(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    #endregion Private Helpers
}
