// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

#pragma warning disable IDE0072 // Add missing cases

namespace Nalix.AutoGenerated;

/// <inheritdoc/>
[Generator]
public sealed class SerializeFormatterGenerator : IIncrementalGenerator
{
    private const string GeneratedFormatterNamespace = "Nalix.AutoGenerated.Formatter";
    private const string GenerateFormatterAttributeName = "GenerateFormatterAttribute";

    private const string SerializeOrderAttributeName = "SerializeOrderAttribute";
    private const string SerializeIgnoreAttributeName = "SerializeIgnoreAttribute";
    private const string SerializeHeaderAttributeName = "SerializeHeaderAttribute";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ITypeSymbol?> provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is TypeDeclarationSyntax { AttributeLists.Count: > 0 } tds &&
                    (tds is ClassDeclarationSyntax or StructDeclarationSyntax) &&
                    !tds.Modifiers.Any(static m =>
                        m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.AbstractKeyword) ||
                        m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.StaticKeyword)),
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static t => t is not null);

        context.RegisterSourceOutput(provider.Collect(), this.Execute);
    }

    private static ITypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        if (context.Node is not TypeDeclarationSyntax typeDef)
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(typeDef) is not ITypeSymbol symbol)
        {
            return null;
        }

        foreach (AttributeData attr in symbol.GetAttributes())
        {
            string? name = attr.AttributeClass?.Name;

            if (name == GenerateFormatterAttributeName)
            {
                return symbol;
            }
        }
        return null;
    }

    private static bool HasStaticCreateMethod(ITypeSymbol type)
    {
        ITypeSymbol? current = type;

        while (current is not null && current.SpecialType == SpecialType.None)
        {
            bool hasCreate = current.GetMembers()
                .OfType<IMethodSymbol>()
                .Any(m => m is
                {
                    Name: "Create",
                    IsStatic: true,
                    Parameters.Length: 0,
                    DeclaredAccessibility: Accessibility.Public or Accessibility.Internal
                });

            if (hasCreate)
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }

    private void Execute(SourceProductionContext context, ImmutableArray<ITypeSymbol?> targets)
    {
        if (targets.IsDefaultOrEmpty)
        {
            return;
        }

        List<(string FullName, string FormatterName)> registeredFormatters = new(targets.Length);

        foreach (ITypeSymbol? type in targets)
        {
            if (type is null)
            {
                continue;
            }

            bool isClass = type.IsReferenceType;
            string className = type.Name;
            string @namespace = type.ContainingNamespace.ToDisplayString();
            string formatterName = $"{className}Formatter";

            if (isClass && !HasStaticCreateMethod(type))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "NALIX059",
                        "Missing static Create() method",
                        "Type '{0}' is marked [GenerateFormatter] but neither it nor any of its base types has a public/internal static Create() method. " +
                        "This is required for the pooling pattern used by LiteSerializer.Fill.",
                        "Nalix.Abstractions.Serialization.GenerateFormatterAttribute",
                        DiagnosticSeverity.Error,
                        true),
                    type.Locations[0],
                    type.ToDisplayString()));

                continue;
            }

            registeredFormatters.Add(($"global::{@namespace}.{className}", $"global::{GeneratedFormatterNamespace}.{formatterName}"));

            List<ISymbol> members = this.GetOrderedMembers(type);
            string interfaceName = isClass ? $"IFillableFormatter<{className}>" : $"IFormatter<{className}>";

            StringBuilder sb = new(4096);
            _ = sb.AppendLine("// <auto-generated/>");
            _ = sb.AppendLine("using System.Runtime.CompilerServices;");
            _ = sb.AppendLine("using Nalix.Codec.Memory;");
            _ = sb.AppendLine("using Nalix.Codec.Serialization;");
            _ = sb.AppendLine("using Nalix.Codec.Extensions;");
            _ = sb.AppendLine($"using {@namespace};");
            _ = sb.AppendLine();
            _ = sb.AppendLine("#pragma warning disable CS1591");
            _ = sb.AppendLine("#nullable enable");
            _ = sb.AppendLine();
            _ = sb.AppendLine($"namespace {GeneratedFormatterNamespace};");
            _ = sb.AppendLine();
            _ = sb.AppendLine("[System.Diagnostics.StackTraceHidden]");
            _ = sb.AppendLine("[System.Diagnostics.DebuggerStepThrough]");
            _ = sb.AppendLine("[System.Runtime.CompilerServices.SkipLocalsInit]");
            _ = sb.AppendLine($"internal sealed class {formatterName} : {interfaceName}");
            _ = sb.AppendLine("{");

            // ==================== Serialize ====================
            _ = sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]");
            _ = sb.AppendLine($"    public void Serialize(ref DataWriter writer, in global::{@namespace}.{className} value)");
            _ = sb.AppendLine("    {");
            if (isClass)
            {
                _ = sb.AppendLine("        System.ArgumentNullException.ThrowIfNull(value);");
                _ = sb.AppendLine();
            }
            if (ImplementsFixedSizeSerializable(type))
            {
                _ = sb.AppendLine($"        writer.Expand(global::{@namespace}.{className}.Size);");
            }
            _ = sb.Append(this.GenerateSerializeBody(members));
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();

            // ==================== Deserialize ====================
            _ = sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]");
            _ = sb.AppendLine($"    public global::{@namespace}.{className} Deserialize(ref DataReader reader)");
            _ = sb.AppendLine("    {");
            if (isClass)
            {
                _ = sb.AppendLine($"        global::{@namespace}.{className} instance = global::{@namespace}.{className}.Create();");
                _ = sb.AppendLine("        this.Fill(ref reader, instance);");
                _ = sb.AppendLine("        return instance;");
            }
            else
            {
                _ = sb.AppendLine($"        global::{@namespace}.{className} instance = default;");
                _ = sb.Append(this.GenerateAssignmentBody(members, "instance"));
                _ = sb.AppendLine("        return instance;");
            }
            _ = sb.AppendLine("    }");

            // ==================== Fill ====================
            if (isClass)
            {
                _ = sb.AppendLine();
                _ = sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]");
                _ = sb.AppendLine($"    public void Fill(ref DataReader reader, global::{@namespace}.{className} value)");
                _ = sb.AppendLine("    {");
                _ = sb.AppendLine("        System.ArgumentNullException.ThrowIfNull(value);");
                _ = sb.AppendLine();
                _ = sb.Append(this.GenerateAssignmentBody(members, "value", true));
                _ = sb.AppendLine("    }");
            }

            _ = sb.AppendLine("}");
            context.AddSource($"{formatterName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        GenerateBootstrapper(context, registeredFormatters);
    }

    private static bool ImplementsFixedSizeSerializable(ITypeSymbol type)
    {
        foreach (INamedTypeSymbol iface in type.AllInterfaces)
        {
            if (iface.Name == "IFixedSizeSerializable" &&
                iface.ContainingNamespace?.ToDisplayString() == "Nalix.Abstractions.Serialization")
            {
                return true;
            }
        }
        return false;
    }

    private string GenerateSerializeBody(List<ISymbol> members)
    {
        StringBuilder code = new(members.Count * 64);

        foreach (ISymbol m in members)
        {
            ITypeSymbol type = GetSymbolType(m);

            if (type.TypeKind == TypeKind.Enum)
            {
                _ = code.AppendLine($"        writer.WriteEnum(value.{m.Name});");
            }
            else if (type.IsUnmanagedType && type.TypeKind == TypeKind.Struct)
            {
                // Custom unmanaged struct
                _ = code.AppendLine($"        writer.WriteUnmanaged(value.{m.Name});");
            }
            else if (type.SpecialType != SpecialType.None && type.SpecialType != SpecialType.System_String)
            {
                // Primitive types (byte, int, bool, float, double, char...)
                _ = code.AppendLine($"        writer.Write(value.{m.Name});");
            }
            else
            {
                // string + complex types + reference types
                _ = code.AppendLine($"        LiteSerializer.Serialize(ref writer, value.{m.Name});");
            }
        }

        return code.ToString();
    }

    private string GenerateAssignmentBody(List<ISymbol> members, string targetName, bool isFillContext = false)
    {
        StringBuilder code = new(members.Count * 80);

        foreach (ISymbol m in members)
        {
            ITypeSymbol type = GetSymbolType(m);
            string memberAccess = $"{targetName}.{m.Name}";

            if (type.TypeKind == TypeKind.Enum)
            {
                _ = code.AppendLine($"        {memberAccess} = reader.{GetEnumReadMethod(type)}<{type.ToDisplayString()}>();");
            }
            else if (type.SpecialType != SpecialType.None && type.SpecialType != SpecialType.System_String)
            {
                // Primitive types
                _ = code.AppendLine($"        {memberAccess} = reader.{GetPrimitiveReadMethod(type)}();");
            }
            else if (type.IsUnmanagedType && type.TypeKind == TypeKind.Struct)
            {
                // Custom unmanaged struct
                _ = code.AppendLine($"        {memberAccess} = reader.ReadUnmanaged<{type.ToDisplayString()}>();");
            }
            else
            {
                // Complex types + string + array + reference types
                if (isFillContext &&
                    type.IsReferenceType &&
                    type.SpecialType != SpecialType.System_String &&
                    type.TypeKind != TypeKind.Array)
                {
                    _ = code.AppendLine($"        if ({memberAccess} is not null)");
                    _ = code.AppendLine("        {");
                    _ = code.AppendLine($"            LiteSerializer.Fill(ref reader, {memberAccess});");
                    _ = code.AppendLine("        }");
                    _ = code.AppendLine("        else");
                    _ = code.AppendLine("        {");
                    _ = code.AppendLine($"            {memberAccess} = LiteSerializer.Deserialize<{type.ToDisplayString()}>(ref reader);");
                    _ = code.AppendLine("        }");
                }
                else
                {
                    _ = code.AppendLine($"        {memberAccess} = LiteSerializer.Deserialize<{type.ToDisplayString()}>(ref reader);");
                }
            }
        }

        return code.ToString();
    }

    private static string GetEnumReadMethod(ITypeSymbol type)
    {
        SpecialType? underlying = ((INamedTypeSymbol)type).EnumUnderlyingType?.SpecialType;

        return underlying switch
        {
            SpecialType.System_SByte => "ReadEnumSByte",
            SpecialType.System_Byte => "ReadEnumByte",
            SpecialType.System_Int16 => "ReadEnumInt16",
            SpecialType.System_UInt16 => "ReadEnumUInt16",
            SpecialType.System_Int32 => "ReadEnumInt32",
            SpecialType.System_UInt32 or _ => "ReadEnumUInt32"
        };
    }

    private static string GetPrimitiveReadMethod(ITypeSymbol type) => type.SpecialType switch
    {
        SpecialType.System_Char => "ReadChar",
        SpecialType.System_Byte => "ReadByte",
        SpecialType.System_SByte => "ReadSByte",
        SpecialType.System_Boolean => "ReadBoolean",
        SpecialType.System_Int16 => "ReadInt16",
        SpecialType.System_Int32 => "ReadInt32",
        SpecialType.System_Int64 => "ReadInt64",
        SpecialType.System_UInt16 => "ReadUInt16",
        SpecialType.System_UInt32 => "ReadUInt32",
        SpecialType.System_UInt64 => "ReadUInt64",
        SpecialType.System_Single => "ReadSingle",
        SpecialType.System_Double => "ReadDouble",
        _ => "ReadUnmanaged"
    };

    private List<ISymbol> GetOrderedMembers(ITypeSymbol type)
    {
        List<ISymbol> allMembers = new(16);
        ITypeSymbol? currentType = type;

        // Walk inheritance chain (supports FrameBase / PacketBase patterns)
        while (currentType is not null && currentType.SpecialType == SpecialType.None)
        {
            ImmutableArray<ISymbol> members = currentType.GetMembers();
            foreach (ISymbol member in members)
            {
                if (member is not (IPropertySymbol or IFieldSymbol))
                {
                    continue;
                }

                bool hasOrder = member.GetAttributes().Any(static a => a.AttributeClass?.Name == SerializeOrderAttributeName);
                bool hasHeader = member.GetAttributes().Any(static a => a.AttributeClass?.Name == SerializeHeaderAttributeName);

                if (!hasHeader && !hasOrder)
                {
                    continue;
                }

                if (member.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
                {
                    // Private field → locate matching public property wrapper (even if marked [SerializeIgnore])
                    // This supports internal header encapsulation patterns used in Nalix packet frames.
                    ITypeSymbol memberType = member is IFieldSymbol f ? f.Type : ((IPropertySymbol)member).Type;

                    IPropertySymbol? publicWrapper = currentType.GetMembers()
                        .OfType<IPropertySymbol>()
                        .FirstOrDefault(p =>
                            p.DeclaredAccessibility == Accessibility.Public &&
                            SymbolEqualityComparer.Default.Equals(p.Type, memberType) &&
                            p.GetAttributes().Any(static a => a.AttributeClass?.Name == SerializeIgnoreAttributeName));

                    if (publicWrapper is not null)
                    {
                        allMembers.Add(publicWrapper);
                        continue;
                    }
                }

                allMembers.Add(member);
            }
            currentType = currentType.BaseType;
        }

        // Separate + order headers first, then payload (stable, deterministic layout)
        IOrderedEnumerable<ISymbol> headers = allMembers
            .Where(m => GetAttribute(m, SerializeHeaderAttributeName) is not null)
            .OrderBy(m => (int)GetAttribute(m, SerializeHeaderAttributeName)!.ConstructorArguments[0].Value!);

        IOrderedEnumerable<ISymbol> payload = allMembers
            .Where(m => GetAttribute(m, SerializeOrderAttributeName) is not null)
            .OrderBy(m => (int)GetAttribute(m, SerializeOrderAttributeName)!.ConstructorArguments[0].Value!);
        return [.. headers, .. payload];
    }

    private static AttributeData? GetAttribute(ISymbol member, string attrName)
    {
        AttributeData? attr = member.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == attrName);
        if (attr is not null)
        {
            return attr;
        }

        // Fallback for property-wrapper pattern: look for attribute on matching private field
        if (member is IPropertySymbol prop)
        {
            return prop.ContainingType.GetMembers()
                .OfType<IFieldSymbol>()
                .FirstOrDefault(f =>
                    SymbolEqualityComparer.Default.Equals(f.Type, prop.Type) &&
                    f.GetAttributes().Any(a => a.AttributeClass?.Name == attrName))
                ?.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == attrName);
        }
        return null;
    }

    private static ITypeSymbol GetSymbolType(ISymbol symbol)
        => symbol is IPropertySymbol p ? p.Type : ((IFieldSymbol)symbol).Type;

    private static void GenerateBootstrapper(SourceProductionContext context, List<(string FullName, string FormatterName)> registered)
    {
        StringBuilder sb = new((registered.Count * 80) + 256);
        _ = sb.AppendLine("using System.Runtime.CompilerServices;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#pragma warning disable CA2255");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("namespace Nalix.AutoGenerated;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("internal static class SerializeFormatterGenerated");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    [ModuleInitializer]");
        _ = sb.AppendLine("    public static void Initialize()");
        _ = sb.AppendLine("    {");
        foreach ((_, string formatterName) in registered)
        {
            _ = sb.AppendLine($"        global::Nalix.Codec.Serialization.LiteSerializer.Register(new {formatterName}());");
        }
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");
        context.AddSource("SerializeFormatterGenerated.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

