// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Nalix.Framework.DataFrames.Chunks;

// ┌───────────────────────────────────────────────────────────────────────────┐
// │  Wire format for each chunk (= 1 normal framed packet)                    │
// │                                                                           │
// │  [2 B LE]  FramedSocket outer frame length                                │
// │  payload:                                                                 │
// │    [2 B LE]  StreamId     — distinguishes parallel streams                │
// │    [2 B LE]  ChunkIndex   — 0-based index                                 │
// │    [2 B LE]  TotalChunks  — known in advance                              │
// │    [1 B]     Flags        — bit0 = IsLastChunk                            │
// │    [N B]     Chunk body   (split automatically)                           │
// │                                                                           │
// │  Overhead / chunk = 2 B (frame) + 7 B (ChunkHeader) = 9 B                 │
// │  PacketFlags.FRAGMENTED is set so the receiver can detect it              │
// └───────────────────────────────────────────────────────────────────────────┘

/// <summary>
/// Fixed-size <b>7-byte</b> header located at the start of the payload for each chunk.
/// <para>
/// <b>Shared contract</b> between SDK (<c>FRAME_SENDER</c> / <c>FRAME_READER</c>)
/// and Server (<c>FramedSocketConnection</c>).
/// Both sides use <see cref="WriteTo"/> when sending and <see cref="ReadFrom"/> when receiving.
/// </para>
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
[method: MethodImpl(MethodImplOptions.AggressiveInlining)]
public readonly struct FragmentHeader(ushort streamId, ushort chunkIndex, ushort totalChunks, bool isLast) : IEquatable<FragmentHeader>
{
    #region Constants

    /// <summary>
    /// Number of bytes the header occupies on the wire (7 bytes).
    /// </summary>
    public const int WireSize = sizeof(ushort) + sizeof(ushort) + sizeof(ushort) + sizeof(byte);

    private const byte FlagIsLast = 0b0000_0001;

    #endregion Constants

    #region Properties

    /// <summary>
    /// Stream ID — generated by <see cref="FragmentStreamId.Next"/>. Never zero.
    /// </summary>
    public readonly ushort StreamId = streamId;

    /// <summary>
    /// Zero-based index of this chunk in the stream.
    /// </summary>
    public readonly ushort ChunkIndex = chunkIndex;

    /// <summary>
    /// Total number of chunks in the stream.
    /// </summary>
    public readonly ushort TotalChunks = totalChunks;

    /// <summary
    /// >Flags byte — bit 0 = IsLastChunk. Other bits reserved for future use.
    /// </summary>
    public readonly byte Flags = isLast ? FlagIsLast : (byte)0;

    /// <summary>
    /// <see langword="true"/> if this is the last chunk.
    /// </summary>
    public bool IsLast => (Flags & FlagIsLast) != 0;

    #endregion Properties

    #region APIs

    /// <summary>
    /// Write the header to <paramref name="dest"/> (little-endian).
    /// Requires <paramref name="dest"/>.Length >= <see cref="WireSize"/>.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void WriteTo(Span<byte> dest)
    {
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(dest, StreamId);
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(dest[2..], ChunkIndex);
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(dest[4..], TotalChunks);
        dest[6] = Flags;
    }

    /// <summary>
    /// Read header from the start of <paramref name="src"/> (little-endian).
    /// Requires <paramref name="src"/>.Length >= <see cref="WireSize"/>.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static FragmentHeader ReadFrom(ReadOnlySpan<byte> src)
        => new(
            streamId: System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(src),
            chunkIndex: System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(src[2..]),
            totalChunks: System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(src[4..]),
            isLast: (src[6] & FlagIsLast) != 0);

    // ── Equality ─────────────────────────────────────────────────────────────

    /// <inheritdoc/>
    public bool Equals(FragmentHeader other)
        => StreamId == other.StreamId && ChunkIndex == other.ChunkIndex
        && TotalChunks == other.TotalChunks && Flags == other.Flags;

    /// <inheritdoc/>
    public override bool Equals(object? obj) => obj is FragmentHeader h && Equals(h);

    /// <inheritdoc/>
    public override int GetHashCode() => HashCode.Combine(StreamId, ChunkIndex, TotalChunks, Flags);

    /// <inheritdoc/>
    public override string ToString() => $"Chunk(stream={StreamId}, {ChunkIndex}/{TotalChunks - 1}, last={IsLast})";

    /// <inheritdoc/>
    public static bool operator ==(FragmentHeader left, FragmentHeader right) => left.Equals(right);

    /// <inheritdoc/>
    public static bool operator !=(FragmentHeader left, FragmentHeader right) => !(left == right);

    #endregion APIs
}
