// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Nalix.Analyzers.Generators.Internal;

namespace Nalix.Analyzers.Generators;

/// <summary>
/// Generates zero-allocation dispatch compilers for packet controllers.
/// </summary>
[Generator]
public sealed class PacketHandlerGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol?> controllers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GET_CONTROLLER_TYPE(ctx))
            .Where(static symbol => symbol is not null);

        IncrementalValueProvider<ImmutableArray<INamedTypeSymbol?>> collected = controllers.Collect();

        context.RegisterSourceOutput(collected, static (spc, source) => Execute(source, spc));
    }

    private static void Execute(ImmutableArray<INamedTypeSymbol?> targets, SourceProductionContext context)
    {
        HashSet<string> seen = new();

        List<INamedTypeSymbol> distinctControllers = [.. targets
            .Where(static p => p is not null)
            .Select(static p => p!)
            .Where(p => seen.Add(p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
            .OrderBy(static p => p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))];

        if (distinctControllers.Count == 0)
        {
            return;
        }

        string generatedNamespace = SourceGenNamespaces.Get(distinctControllers[0]);
        string assemblyName = distinctControllers[0].ContainingAssembly.Name ?? "Nalix";
        string safeAssemblyName = new([.. assemblyName.Select(c => char.IsLetterOrDigit(c) ? c : '_')]);

        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("// Copyright (c) 2026 PPN Corporation. All rights reserved.");
        _ = sb.AppendLine("// Licensed under the Apache License, Version 2.0.");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#pragma warning disable CS1591");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using System.Threading.Tasks;");
        _ = sb.AppendLine("using System.Runtime.CompilerServices;");
        _ = sb.AppendLine("using Nalix.Runtime.Dispatching;");
        _ = sb.AppendLine("using Nalix.Abstractions.Networking.Packets;");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"namespace {generatedNamespace};");
        _ = sb.AppendLine();

        foreach (INamedTypeSymbol controller in distinctControllers)
        {
            EMIT_COMPILER(sb, controller);
            EMIT_PARTIAL_CLASS(context, controller);
        }

        _ = sb.AppendLine($"internal static class PacketHandlerGenerated");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    [ModuleInitializer]");
        _ = sb.AppendLine("    internal static void Initialize()");
        _ = sb.AppendLine("    {");

        foreach (INamedTypeSymbol controller in distinctControllers)
        {
            string classFullName = controller.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string compilerName = $"__Compiler_{GetSafeName(classFullName)}";

            _ = sb.AppendLine($"        PacketHandlerRegistry.Register(typeof({classFullName}), new {compilerName}());");
        }

        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        context.AddSource($"PacketHandlerGenerated.cs", sb.ToString());
    }

    private static void EMIT_COMPILER(StringBuilder sb, INamedTypeSymbol controller)
    {
        string classFullName = controller.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string compilerName = $"__Compiler_{GetSafeName(classFullName)}";

        _ = sb.AppendLine($"internal sealed class {compilerName} : IPacketHandlerCompiler");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    public void InitializeDependencies()");
        _ = sb.AppendLine("    {");
        List<ISymbol> injectedMembers = [.. controller.GetMembers().Where(m => (m is IFieldSymbol || m is IPropertySymbol) && m.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == KnownNames.InjectAttributeMetadataName))];
        if (injectedMembers.Count > 0)
        {
            _ = sb.AppendLine($"        {classFullName}.__InitializeDependencies();");
        }
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    public void Build<TPacket>(global::Nalix.Runtime.Dispatching.IPacketHandlerBuilder<TPacket> builder, global::System.Func<object> factory) where TPacket : global::Nalix.Abstractions.Networking.Packets.IPacket");
        _ = sb.AppendLine("    {");

        // Find methods with PacketOpcodeAttribute
        foreach (IMethodSymbol method in controller.GetMembers().OfType<IMethodSymbol>())
        {
            if (method.DeclaredAccessibility != Accessibility.Public && method.DeclaredAccessibility != Accessibility.Internal)
            {
                continue;
            }

            AttributeData? opcodeAttr = method.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == KnownNames.PacketOpcodeAttributeMetadataName);

            if (opcodeAttr == null || opcodeAttr.ConstructorArguments.Length == 0)
            {
                continue;
            }

            // Get Opcode Value
            object? val = opcodeAttr.ConstructorArguments[0].Value;
            if (val == null)
            {
                continue;
            }

            ushort opcodeVal = Convert.ToUInt16(val);

            // Get Packet Type from parameter
            if (method.Parameters.Length != 1)
            {
                continue;
            }

            IParameterSymbol param = method.Parameters[0];
            INamedTypeSymbol? packetType = null;
            bool isGenericContext = false;

            if (param.Type is INamedTypeSymbol namedParam && namedParam.IsGenericType && namedParam.TypeArguments.Length == 1)
            {
                packetType = namedParam.TypeArguments[0] as INamedTypeSymbol;
                isGenericContext = true;
            }

            string expectedPacketTypeStr = packetType != null
                ? $"typeof({packetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})"
                : "null";

            string returnTypeStr = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            // Generate Metadata
            string metadataExpr = EmitMetadataExpression(method, opcodeVal);

            _ = sb.AppendLine($"        builder.RegisterHandler(");
            _ = sb.AppendLine($"            opCode: {opcodeVal},");
            _ = sb.AppendLine($"            metadata: {metadataExpr},");
            _ = sb.AppendLine($"            methodName: \"{method.Name}\",");
            // Check if controller has injected fields
            bool hasInjectedFields = controller.GetMembers().Any(m => (m is IFieldSymbol || m is IPropertySymbol) && m.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == KnownNames.InjectAttributeMetadataName));

            string instanceArg = method.IsStatic ? "null" : (hasInjectedFields ? $"{classFullName}.Instance" : "factory()");
            _ = sb.AppendLine($"            instance: {instanceArg},");
            _ = sb.AppendLine($"            returnType: typeof({returnTypeStr}),");
            _ = sb.AppendLine($"            expectedPacketType: {expectedPacketTypeStr},");

            // Invoker delegate
            _ = sb.AppendLine($"            invoker: static async (instance, context) =>");
            _ = sb.AppendLine($"            {{");

            string instanceCast = method.IsStatic ? "" : $"(({classFullName})instance!).";
            string typeCall = method.IsStatic ? $"{classFullName}." : instanceCast;
            string contextCast;
            if (isGenericContext && packetType != null)
            {
                string pType = packetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                _ = sb.AppendLine($"                var concretePacket = ({pType})(object)context.Packet;");
                _ = sb.AppendLine($"                var concreteContext = global::Nalix.Runtime.Dispatching.PacketContextBridge.Create<{pType}, TPacket>(");
                _ = sb.AppendLine($"                    (global::Nalix.Runtime.Dispatching.PacketContext<TPacket>)context, concretePacket);");
                contextCast = "concreteContext";
            }
            else
            {
                contextCast = "(global::Nalix.Abstractions.Networking.Packets.IPacketContext)context";
            }

            if (returnTypeStr == "void")
            {
                _ = sb.AppendLine($"                {typeCall}{method.Name}({contextCast});");
                _ = sb.AppendLine($"                return null;");
            }
            else if (method.ReturnType.Name is "ValueTask" or "Task" && method.ReturnType is INamedTypeSymbol namedRet && !namedRet.IsGenericType)
            {
                _ = sb.AppendLine($"                await {typeCall}{method.Name}({contextCast});");
                _ = sb.AppendLine($"                return null;");
            }
            else
            {
                if (method.ReturnType.Name is "ValueTask" or "Task")
                {
                    _ = sb.AppendLine($"                return await {typeCall}{method.Name}({contextCast});");
                }
                else
                {
                    _ = sb.AppendLine($"                return {typeCall}{method.Name}({contextCast});");
                }
            }

            _ = sb.AppendLine($"            }});");
        }

        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");
        _ = sb.AppendLine();
    }

    private static void EMIT_PARTIAL_CLASS(SourceProductionContext context, INamedTypeSymbol controller)
    {
        List<ISymbol> injectedMembers = [.. controller.GetMembers().Where(m => (m is IFieldSymbol || m is IPropertySymbol) && m.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == KnownNames.InjectAttributeMetadataName))];
        if (injectedMembers.Count == 0)
        {
            return;
        }

        string classFullName = controller.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string safeName = GetSafeName(classFullName);
        string namespaceName = controller.ContainingNamespace.ToDisplayString();

        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"namespace {namespaceName}");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine($"    partial class {controller.Name}");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]");
        _ = sb.AppendLine("        internal static void __InitializeDependencies()");
        _ = sb.AppendLine("        {");
        foreach (ISymbol member in injectedMembers)
        {
            string typeName = member switch
            {
                IFieldSymbol f => f.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                IPropertySymbol p => p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                _ => ""
            };
            string prefix = member.IsStatic ? "" : "Instance.";
            _ = sb.AppendLine($"            {prefix}{member.Name} = global::Nalix.Framework.Injection.InstanceManager.Instance.GetExistingInstance<{typeName}>()!;");
        }
        _ = sb.AppendLine("        }");

        if (!controller.IsStatic)
        {
            _ = sb.AppendLine();
            _ = sb.AppendLine($"        private static {classFullName}? __s_instance;");
            _ = sb.AppendLine($"        internal static {classFullName} Instance => __s_instance ??= new {classFullName}();");
        }

        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        context.AddSource($"{safeName}_Inject.g.cs", sb.ToString());
    }

    private static string EmitMetadataExpression(IMethodSymbol method, ushort opcode)
    {
        ImmutableArray<AttributeData> attrs = method.GetAttributes();

        string tTimeout = "null";
        string tPermission = "null";
        string tEncryption = "null";
        string tRate = "null";
        string tConcurrency = "null";
        string tTransport = "null";

        List<string> customAttributesList = new();

        foreach (AttributeData a in attrs)
        {
            string? name = a.AttributeClass?.ToDisplayString();
            if (name == null)
            {
                continue;
            }

            if (name == KnownNames.PacketOpcodeAttributeMetadataName)
            {
                continue;
            }
            else if (name.StartsWith("System.Runtime.CompilerServices"))
            {
                continue;
            }
            else if (name.StartsWith("System.Diagnostics"))
            {
                continue;
            }

            if (name == KnownNames.PacketTimeoutAttributeMetadataName && a.ConstructorArguments.Length > 0)
            {
                tTimeout = $"new global::Nalix.Abstractions.Networking.Packets.PacketTimeoutAttribute((int){a.ConstructorArguments[0].Value})";
            }
            else if (name == KnownNames.PacketPermissionAttributeMetadataName && a.ConstructorArguments.Length > 0)
            {
                tPermission = $"new global::Nalix.Abstractions.Networking.Packets.PacketPermissionAttribute((global::Nalix.Abstractions.Security.PermissionLevel){a.ConstructorArguments[0].Value})";
            }
            else if (name == KnownNames.PacketEncryptionAttributeMetadataName && a.ConstructorArguments.Length > 0)
            {
                tEncryption = $"new global::Nalix.Abstractions.Networking.Packets.PacketEncryptionAttribute({a.ConstructorArguments[0].Value?.ToString()?.ToLowerInvariant()})";
            }
            else if (name == KnownNames.PacketRateLimitAttributeMetadataName && a.ConstructorArguments.Length > 0)
            {
                int rps = (int)a.ConstructorArguments[0].Value!;
                double burst = a.ConstructorArguments.Length > 1 ? (double)a.ConstructorArguments[1].Value! : 1.0;
                tRate = $"new global::Nalix.Abstractions.Networking.Packets.PacketRateLimitAttribute({rps}, {burst})";
            }
            else if (name == KnownNames.PacketConcurrencyLimitAttributeMetadataName)
            {
                if (a.ConstructorArguments.Length > 0)
                {
                    tConcurrency = $"new global::Nalix.Abstractions.Networking.Packets.PacketConcurrencyLimitAttribute((int){a.ConstructorArguments[0].Value})";
                }
                else
                {
                    tConcurrency = $"new global::Nalix.Abstractions.Networking.Packets.PacketConcurrencyLimitAttribute()";
                }
            }
            else if (name == KnownNames.PacketTransportAttributeMetadataName && a.ConstructorArguments.Length > 0)
            {
                tTransport = $"new global::Nalix.Abstractions.Networking.Packets.PacketTransportAttribute((global::Nalix.Abstractions.Networking.NetworkTransport){a.ConstructorArguments[0].Value})";
            }
            else
            {
                // Parse and render custom attribute
                string initCode = RenderCustomAttribute(a);
                if (!string.IsNullOrEmpty(initCode))
                {
                    customAttributesList.Add($"{{ typeof(global::{name}), {initCode} }}");
                }
            }
        }

        string customAttributesExpr = "null";
        if (customAttributesList.Count > 0)
        {
            customAttributesExpr = $@"new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Attribute>()
                {{
                    {string.Join(",\n                    ", customAttributesList)}
                }}";
        }

        return $@"new global::Nalix.Abstractions.Networking.Packets.PacketMetadata(
                opCode: new global::Nalix.Abstractions.Networking.Packets.PacketOpcodeAttribute({opcode}),
                timeout: {tTimeout},
                permission: {tPermission},
                encryption: {tEncryption},
                rateLimit: {tRate},
                concurrencyLimit: {tConcurrency},
                transport: {tTransport},
                customAttributes: {customAttributesExpr})";
    }

    private static string RenderCustomAttribute(AttributeData attr)
    {
        if (attr.AttributeClass == null)
        {
            return "";
        }

        string typeName = attr.AttributeClass.ToDisplayString();

        List<string> ctorArgs = new();
        foreach (TypedConstant arg in attr.ConstructorArguments)
        {
            ctorArgs.Add(RenderTypedConstant(arg));
        }

        List<string> namedArgs = new();
        foreach (System.Collections.Generic.KeyValuePair<string, TypedConstant> namedArg in attr.NamedArguments)
        {
            namedArgs.Add($"{namedArg.Key} = {RenderTypedConstant(namedArg.Value)}");
        }

        string ctorString = string.Join(", ", ctorArgs);
        string initString = namedArgs.Count > 0 ? $" {{ {string.Join(", ", namedArgs)} }}" : "";

        return $"new global::{typeName}({ctorString}){initString}";
    }

    private static string RenderTypedConstant(TypedConstant constant)
    {
        if (constant.IsNull)
        {
            return "null";
        }

        if (constant.Kind == TypedConstantKind.Array)
        {
            string elementType = ((IArrayTypeSymbol)constant.Type!).ElementType.ToDisplayString();
            IEnumerable<string> elements = constant.Values.Select(RenderTypedConstant);
            return $"new global::{elementType}[] {{ {string.Join(", ", elements)} }}";
        }

        if (constant.Kind == TypedConstantKind.Enum)
        {
            return $"(global::{constant.Type!.ToDisplayString()}){constant.Value}";
        }

        if (constant.Kind == TypedConstantKind.Type)
        {
            return $"typeof(global::{((ITypeSymbol)constant.Value!).ToDisplayString()})";
        }

        if (constant.Value is string s)
        {
            return Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(s, true);
        }

        if (constant.Value is bool b)
        {
            return b ? "true" : "false";
        }

        return constant.Value?.ToString() ?? "null";
    }

    private static string GetSafeName(string name) => name.Replace("global::", "").Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace(":", "_");

    private static INamedTypeSymbol? GET_CONTROLLER_TYPE(GeneratorSyntaxContext context)
    {
        if (context.Node is not TypeDeclarationSyntax typeDecl)
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(typeDecl) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.IsAbstract || symbol.TypeKind == TypeKind.Interface || symbol.IsGenericType)
        {
            return null;
        }

        if (!symbol.GetAttributes().Any(static attr => attr.AttributeClass?.ToDisplayString() == KnownNames.PacketControllerAttributeMetadataName))
        {
            return null;
        }

        return symbol;
    }
}
