// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Nalix.Analyzers.Generators.Internal;

namespace Nalix.Analyzers.Generators;

/// <summary>
/// Generates packet registration and fast-dispatch code for packets marked with PacketAttribute.
/// </summary>
[Generator]
public sealed class PacketRegistryGenerator : IIncrementalGenerator
{
    public readonly struct PacketRegistryModel : IEquatable<PacketRegistryModel>
    {
        public string FullyQualifiedName { get; }
        public string ErrorMessageName { get; }
        public string GeneratedNamespace { get; }

        public PacketRegistryModel(string fullyQualifiedName, string errorMessageName, string generatedNamespace)
        {
            this.FullyQualifiedName = fullyQualifiedName;
            this.ErrorMessageName = errorMessageName;
            this.GeneratedNamespace = generatedNamespace;
        }

        public bool Equals(PacketRegistryModel other) =>
            this.FullyQualifiedName == other.FullyQualifiedName &&
            this.ErrorMessageName == other.ErrorMessageName &&
            this.GeneratedNamespace == other.GeneratedNamespace;

        public override bool Equals(object obj) => obj is PacketRegistryModel other && this.Equals(other);
        public override int GetHashCode() => (this.FullyQualifiedName, this.ErrorMessageName, this.GeneratedNamespace).GetHashCode();
    }

    #region Constants and Diagnostics

    #endregion Constants and Diagnostics

    #region IIncrementalGenerator Implementation

    /// <summary>
    /// Registers the incremental source-generation pipeline.
    /// </summary>
    /// <param name="context">The Roslyn incremental generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<PacketRegistryModel> packets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                KnownNames.PacketAttributeMetadataName,
                predicate: static (node, _) => node is TypeDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => GET_PACKET_TYPE(ctx))
            .Where(static symbol => symbol.FullyQualifiedName != null);

        IncrementalValueProvider<ImmutableArray<PacketRegistryModel>> collected = packets.Collect();

        context.RegisterSourceOutput(collected, static (spc, source) => Execute(source, spc));
    }

    #endregion IIncrementalGenerator Implementation

    #region Private Helpers

    private static void Execute(ImmutableArray<PacketRegistryModel> targets, SourceProductionContext context)
    {
        HashSet<string> seen = new();

        List<PacketRegistryModel> distinctPackets = [.. targets
            .Where(p => p.FullyQualifiedName != null && seen.Add(p.FullyQualifiedName))
            .OrderBy(static p => p.FullyQualifiedName)];

        if (distinctPackets.Count == 0)
        {
            return;
        }

        string generatedNamespace = distinctPackets[0].GeneratedNamespace;

        EMIT_BOOTSTRAP(context, distinctPackets, generatedNamespace);
    }

    private static PacketRegistryModel GET_PACKET_TYPE(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol symbol)
        {
            return default;
        }

        if (symbol.IsAbstract || symbol.TypeKind == TypeKind.Interface || symbol.IsGenericType)
        {
            return default;
        }

        if (!INHERITS_PACKET_BASE_OF_SELF(symbol))
        {
            return default;
        }

        return new PacketRegistryModel(
            symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            symbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            SourceGenNamespaces.Get(symbol));
    }

    private static bool INHERITS_PACKET_BASE_OF_SELF(INamedTypeSymbol symbol)
    {
        INamedTypeSymbol? current = symbol.BaseType;
        while (current is not null)
        {
            if (current.Name == KnownNames.PacketBaseName &&
                current.ContainingNamespace.ToDisplayString() == KnownNames.PacketBaseNamespace &&
                current.TypeArguments.Length == 1 &&
                SymbolEqualityComparer.Default.Equals(current.TypeArguments[0], symbol))
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }

    private static void EMIT_BOOTSTRAP(SourceProductionContext context, IReadOnlyList<PacketRegistryModel> targets, string generatedNamespace)
    {
        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("// Copyright (c) 2026 PPN Corporation. All rights reserved.");
        _ = sb.AppendLine("// Licensed under the Apache License, Version 2.0.");
        _ = sb.AppendLine();
        _ = sb.AppendLine("// DO NOT EDIT MANUALLY.");
        _ = sb.AppendLine("// Design goals:");
        _ = sb.AppendLine("// - Zero runtime reflection");
        _ = sb.AppendLine("// - O(1) packet dispatch");
        _ = sb.AppendLine("// - Allocation-free hot path");
        _ = sb.AppendLine("// - AOT-friendly code generation");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#pragma warning disable CS1591");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System.Runtime.CompilerServices;");
        _ = sb.AppendLine("using System.Threading;");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"namespace {generatedNamespace};");
        _ = sb.AppendLine();
        _ = sb.AppendLine("internal static class PacketRegistryGenerated");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    private static int s_registered;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    // Ensures packet registration happens automatically at module load time.");
        _ = sb.AppendLine("    // This avoids manual initialization and guarantees availability before any network usage.");
        _ = sb.AppendLine("    [ModuleInitializer]");
        _ = sb.AppendLine("    internal static void Initialize() => Register();");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    internal static void Register()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (Interlocked.Exchange(ref s_registered, 1) != 0)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();

        foreach (PacketRegistryModel packet in targets)
        {
            _ = sb.AppendLine($"        global::{KnownNames.PacketBaseNamespace}.{KnownNames.PacketRegistryName}.RegisterGenerated<{packet.FullyQualifiedName}>(");
            _ = sb.AppendLine($"            \"{ESCAPE(packet.ErrorMessageName)}\",");
            _ = sb.AppendLine($"            static raw => {packet.FullyQualifiedName}.Deserialize(raw));");
            _ = sb.AppendLine();
        }

        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        context.AddSource("PacketRegistryGenerated.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string ESCAPE(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    #endregion Private Helpers
}
