// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Nalix.Analyzers.Generators.Internal;

namespace Nalix.Analyzers.Generators;

/// <summary>
/// Generates packet registration and fast-dispatch code for packets marked with PacketAttribute.
/// </summary>
[Generator]
public sealed class PacketRegistryGenerator : IIncrementalGenerator
{
    #region Constants and Diagnostics

    #endregion Constants and Diagnostics

    #region IIncrementalGenerator Implementation

    /// <summary>
    /// Registers the incremental source-generation pipeline.
    /// </summary>
    /// <param name="context">The Roslyn incremental generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol?> packets = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax { AttributeLists.Count: > 0, BaseList: not null },
                transform: static (ctx, _) => GET_PACKET_TYPE(ctx))
            .Where(static symbol => symbol is not null);

        IncrementalValueProvider<System.Collections.Immutable.ImmutableArray<INamedTypeSymbol?>> collected = packets.Collect();

        context.RegisterSourceOutput(collected, static (spc, source) => Execute(source, spc));
    }

    #endregion IIncrementalGenerator Implementation

    #region Private Helpers

    private static void Execute(ImmutableArray<INamedTypeSymbol?> targets, SourceProductionContext context)
    {
        HashSet<string> seen = new();

        List<INamedTypeSymbol> distinctPackets = [.. targets
            .Where(static p => p is not null)
            .Select(static p => p!)
            .Where(p => seen.Add(p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
            .OrderBy(static p => p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))];

        if (distinctPackets.Count == 0)
        {
            return;
        }

        string generatedNamespace = SourceGenNamespaces.Get(distinctPackets[0]);

        EMIT_BOOTSTRAP(context, distinctPackets, generatedNamespace);
    }

    private static INamedTypeSymbol? GET_PACKET_TYPE(GeneratorSyntaxContext context)
    {
        if (context.Node is not TypeDeclarationSyntax typeDecl)
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(typeDecl) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.IsAbstract || symbol.TypeKind == TypeKind.Interface || symbol.IsGenericType)
        {
            return null;
        }

        if (!HAS_PACKET_ATTRIBUTE(symbol))
        {
            return null;
        }

        return INHERITS_PACKET_BASE_OF_SELF(symbol) ? symbol : null;
    }

    private static bool HAS_PACKET_ATTRIBUTE(INamedTypeSymbol symbol) =>
        symbol.GetAttributes().Any(static attr => attr.AttributeClass?.ToDisplayString() == KnownNames.PacketAttributeMetadataName);

    private static bool INHERITS_PACKET_BASE_OF_SELF(INamedTypeSymbol symbol)
    {
        INamedTypeSymbol? current = symbol.BaseType;
        while (current is not null)
        {
            if (current.Name == KnownNames.PacketBaseName &&
                current.ContainingNamespace.ToDisplayString() == KnownNames.PacketBaseNamespace &&
                current.TypeArguments.Length == 1 &&
                SymbolEqualityComparer.Default.Equals(current.TypeArguments[0], symbol))
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }

    private static void EMIT_BOOTSTRAP(SourceProductionContext context, IReadOnlyList<INamedTypeSymbol> targets, string generatedNamespace)
    {
        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("// Copyright (c) 2026 PPN Corporation. All rights reserved.");
        _ = sb.AppendLine("// Licensed under the Apache License, Version 2.0.");
        _ = sb.AppendLine();
        _ = sb.AppendLine("// DO NOT EDIT MANUALLY.");
        _ = sb.AppendLine("// Design goals:");
        _ = sb.AppendLine("// - Zero runtime reflection");
        _ = sb.AppendLine("// - O(1) packet dispatch");
        _ = sb.AppendLine("// - Allocation-free hot path");
        _ = sb.AppendLine("// - AOT-friendly code generation");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#pragma warning disable CS1591");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System.Runtime.CompilerServices;");
        _ = sb.AppendLine("using System.Threading;");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"namespace {generatedNamespace};");
        _ = sb.AppendLine();
        _ = sb.AppendLine("internal static class PacketRegistryGenerated");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    private static int s_registered;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    // Ensures packet registration happens automatically at module load time.");
        _ = sb.AppendLine("    // This avoids manual initialization and guarantees availability before any network usage.");
        _ = sb.AppendLine("    [ModuleInitializer]");
        _ = sb.AppendLine("    internal static void Initialize() => Register();");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    internal static void Register()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (Interlocked.Exchange(ref s_registered, 1) != 0)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();

        foreach (INamedTypeSymbol packet in targets)
        {
            string typeName = packet.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string fullName = packet.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
            
            _ = sb.AppendLine($"        global::{KnownNames.PacketBaseNamespace}.{KnownNames.PacketRegistryName}.RegisterGenerated<{typeName}>(");
            _ = sb.AppendLine($"            \"{ESCAPE(fullName)}\",");
            _ = sb.AppendLine($"            static raw => {typeName}.Deserialize(raw));");
            _ = sb.AppendLine();
        }

        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        context.AddSource("PacketRegistryGenerated.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string ESCAPE(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    #endregion Private Helpers
}
