// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Nalix.Analyzers.Generators.Internal;

namespace Nalix.Analyzers.Generators;

[Generator]
public sealed class RpcClientGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> rpcServiceDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsInterfaceWithAttributes(s),
                transform: static (ctx, _) => GetRpcServiceTypeSymbol(ctx))
            .Where(static m => m is not null)!;

        context.RegisterSourceOutput(rpcServiceDeclarations, static (spc, typeSymbol) => Execute(spc, typeSymbol));
    }

    private static bool IsInterfaceWithAttributes(SyntaxNode node) => node is InterfaceDeclarationSyntax interfaceDecl && interfaceDecl.AttributeLists.Count > 0;

    private static INamedTypeSymbol? GetRpcServiceTypeSymbol(GeneratorSyntaxContext context)
    {
        InterfaceDeclarationSyntax interfaceDecl = (InterfaceDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(interfaceDecl) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        foreach (AttributeData attribute in symbol.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() == KnownNames.RpcServiceAttributeMetadataName)
            {
                return symbol;
            }
        }
        return null;
    }

    private static void Execute(SourceProductionContext context, INamedTypeSymbol typeSymbol)
    {
        string interfaceNamespace = typeSymbol.ContainingNamespace.IsGlobalNamespace ? "" : typeSymbol.ContainingNamespace.ToDisplayString();
        string interfaceName = typeSymbol.Name;
        string className = $"{interfaceName}_RpcClient";
        string cleanInterfaceName = interfaceName.StartsWith("I") ? interfaceName.Substring(1) : interfaceName;
        if (interfaceName.StartsWith("I") && interfaceName.Length > 1 && char.IsUpper(interfaceName[1]))
        {
            className = $"{cleanInterfaceName}_RpcClient";
        }

        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using System.Threading;");
        _ = sb.AppendLine("using System.Threading.Tasks;");
        _ = sb.AppendLine("using Nalix.SDK.Transport;");
        _ = sb.AppendLine("using Nalix.SDK.Transport.Rpc;");
        _ = sb.AppendLine("using Nalix.SDK.Transport.Extensions;");
        _ = sb.AppendLine("using Nalix.SDK.Options;");
        _ = sb.AppendLine();

        if (!string.IsNullOrEmpty(interfaceNamespace))
        {
            _ = sb.AppendLine($"namespace {interfaceNamespace}");
            _ = sb.AppendLine("{");
        }

        _ = sb.AppendLine($"    /// <summary>");
        _ = sb.AppendLine($"    /// Auto-generated RPC client for <see cref=\"{interfaceName}\"/>.");
        _ = sb.AppendLine($"    /// </summary>");
        _ = sb.AppendLine($"    internal sealed class {className} : {interfaceName}");
        _ = sb.AppendLine($"    {{");
        _ = sb.AppendLine($"        private readonly TransportSession _session;");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"        public {className}(TransportSession session)");
        _ = sb.AppendLine($"        {{");
        _ = sb.AppendLine($"            _session = session;");
        _ = sb.AppendLine($"        }}");
        _ = sb.AppendLine();

        foreach (ISymbol member in typeSymbol.GetMembers())
        {
            if (member is not IMethodSymbol method || method.MethodKind != MethodKind.Ordinary)
            {
                continue;
            }

            GenerateMethod(sb, method);
        }

        _ = sb.AppendLine($"    }}");
        _ = sb.AppendLine();

        // Generate ModuleInitializer to register the factory
        _ = sb.AppendLine($"    internal static class {className}Initializer");
        _ = sb.AppendLine($"    {{");
        _ = sb.AppendLine($"        [System.Runtime.CompilerServices.ModuleInitializer]");
        _ = sb.AppendLine($"        public static void Initialize()");
        _ = sb.AppendLine($"        {{");
        _ = sb.AppendLine($"            Nalix.SDK.Transport.Extensions.RpcExtensions.RegisterFactory(typeof({interfaceName}), session => new {className}(session));");
        _ = sb.AppendLine($"        }}");
        _ = sb.AppendLine($"    }}");

        if (!string.IsNullOrEmpty(interfaceNamespace))
        {
            _ = sb.AppendLine("}");
        }

        context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateMethod(StringBuilder sb, IMethodSymbol method)
    {
        string returnType = method.ReturnType.ToDisplayString();
        string methodName = method.Name;

        List<string> parameters = new();
        _ = new List<string>();

        bool isValueTask = returnType == "System.Threading.Tasks.ValueTask" || returnType == "ValueTask";
        bool isRpcCall = returnType.StartsWith("Nalix.SDK.Transport.Rpc.RpcCall");
        bool isRpcStream = returnType.StartsWith("Nalix.SDK.Transport.Rpc.RpcStream");

        string? packetArg = null;
        string? encryptArg = null;
        string? ctArg = null;
        string? optionsArg = null;

        foreach (IParameterSymbol param in method.Parameters)
        {
            string paramType = param.Type.ToDisplayString();
            string paramName = param.Name;

            string defaultVal = param.HasExplicitDefaultValue
                ? (param.ExplicitDefaultValue == null ? "null" : param.ExplicitDefaultValue.ToString().ToLower())
                : "";

            string paramDecl = $"{paramType} {paramName}";
            if (!string.IsNullOrEmpty(defaultVal))
            {
                paramDecl += $" = {defaultVal}";
            }

            parameters.Add(paramDecl);

            if (packetArg == null) // First parameter is always IPacket
            {
                packetArg = paramName;
            }
            else if (paramType == "bool?")
            {
                encryptArg = paramName;
            }
            else if (paramType == "System.Threading.CancellationToken")
            {
                ctArg = paramName;
            }
            else if (paramType == "Nalix.SDK.Options.RequestOptions?")
            {
                optionsArg = paramName;
            }
        }

        string methodSignature = $"        public {returnType} {methodName}({string.Join(", ", parameters)})";
        _ = sb.AppendLine(methodSignature);
        _ = sb.AppendLine($"        {{");

        if (isValueTask)
        {
            string encryptPass = encryptArg ?? "null";
            string ctPass = ctArg ?? "default";
            _ = sb.AppendLine($"            return new ValueTask(_session.SendAsync({packetArg}, encrypt: {encryptPass}, ct: {ctPass}));");
        }
        else if (isRpcCall || isRpcStream)
        {
            string genericArgs = "";
            if (method.ReturnType is INamedTypeSymbol namedReturn && namedReturn.TypeArguments.Length > 0)
            {
                genericArgs = $"<{namedReturn.TypeArguments[0].ToDisplayString()}>";
            }

            string optPass = optionsArg ?? "null";
            string typeName = isRpcCall ? "RpcCall" : "RpcStream";
            _ = sb.AppendLine($"            return new {typeName}{genericArgs}(_session, {packetArg}, {optPass});");
        }

        _ = sb.AppendLine($"        }}");
        _ = sb.AppendLine();
    }
}
