<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nalix.Benchmarks.Shared\Nalix.Benchmarks.Shared.csproj" />
    <ProjectReference Include="..\..\src\Nalix.Codec\Nalix.Codec.csproj" />
    <ProjectReference Include="..\..\analyzers\Nalix.Analyzers.Generators\Nalix.Analyzers.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" GlobalPropertiesToRemove="PublishAot;PublishTrimmed;IsTrimmable;IsAotCompatible" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="2.5.187" />
    <PackageReference Include="MemoryPack" Version="1.21.3" />
  </ItemGroup>
</Project>
