<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>Backend</RootNamespace>
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
		<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>

		<ApplicationIcon>app.ico</ApplicationIcon>

		<Optimize>true</Optimize>
		<TieredCompilation>true</TieredCompilation>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Nalix.SDK\Nalix.SDK.csproj" />
		<ProjectReference Include="..\..\src\Nalix.Logging\Nalix.Logging.csproj" />
		<ProjectReference Include="..\..\src\Nalix.Network\Nalix.Network.csproj" />
		<ProjectReference Include="..\..\src\Nalix.Runtime\Nalix.Runtime.csproj" />
		<ProjectReference Include="..\..\src\Nalix.Hosting\Nalix.Hosting.csproj" />
		<ProjectReference Include="..\..\src\Nalix.Framework\Nalix.Framework.csproj" />
		<ProjectReference Include="..\..\tools\Nalix.LoadTester.Contracts\Nalix.LoadTester.Contracts.csproj" />
		
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
		
		<ProjectReference Include="..\..\src\Nalix.Analyzers.Generators\Nalix.Analyzers.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" GlobalPropertiesToRemove="PublishAot;PublishTrimmed;IsTrimmable;IsAotCompatible;RuntimeIdentifier;RuntimeIdentifiers" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Nalix.Observability.Contracts">
			<HintPath>..\dll\Nalix.Observability.Contracts.dll</HintPath>
		</Reference>
		<Reference Include="Nalix.Observability.Handlers">
			<HintPath>..\dll\Nalix.Observability.Handlers.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
