// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using System;
using System.Buffers.Binary;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using Nalix.Abstractions.Primitives;
using Nalix.Codec.Security.Hashing;
using Nalix.Environment.Random;

namespace Nalix.Codec.Security;

/// <summary>
/// Provides high-performance cryptographic proof-of-work (PoW) generation and verification.
/// </summary>
public static class ProofOfWork
{
    private static readonly byte[] s_hmacKey = Csprng.GetBytes(32);

    /// <summary>
    /// Creates a stateless PoW challenge bound to the specific connection ID.
    /// </summary>
    /// <param name="difficulty">The required number of leading zero bits.</param>
    /// <param name="connectionId">The connection ID to bind this challenge to.</param>
    /// <param name="timestampTicks">The current timestamp.</param>
    /// <returns>A tuple containing the generated Nonce and the server-signed MAC.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (Bytes32 Nonce, Bytes32 Mac) CreateChallenge(byte difficulty, ulong connectionId, long timestampTicks)
    {
        Span<byte> clientNonceBytes = stackalloc byte[Bytes32.Size];
        Csprng.Fill(clientNonceBytes);
        Bytes32 nonce = new(clientNonceBytes);

        // Payload: Nonce (32) | Difficulty (1) | Timestamp (8) | ConnectionId (8) = 49 bytes
        Span<byte> payload = stackalloc byte[49];
        nonce.AsSpan().CopyTo(payload);
        payload[32] = difficulty;
        BinaryPrimitives.WriteInt64LittleEndian(payload.Slice(33, 8), timestampTicks);
        BinaryPrimitives.WriteUInt64LittleEndian(payload.Slice(41, 8), connectionId);

        Span<byte> macBytes = stackalloc byte[32];
        HmacKeccak256.Compute(s_hmacKey, payload, macBytes);

        return (nonce, new Bytes32(macBytes));
    }

    /// <summary>
    /// Verifies the submitted Proof-of-Work solution.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public static bool VerifySolution(
        ReadOnlySpan<byte> nonce,
        byte difficulty,
        long timestampTicks,
        ulong connectionId,
        ReadOnlySpan<byte> providedMac,
        long solution)
    {
        if (nonce.Length != 32 || providedMac.Length != 32)
        {
            return false;
        }

        // 1. Verify the MAC to ensure the challenge was generated by us and for this specific connection.
        Span<byte> payload = stackalloc byte[49];
        nonce.CopyTo(payload);
        payload[32] = difficulty;
        BinaryPrimitives.WriteInt64LittleEndian(payload.Slice(33, 8), timestampTicks);
        BinaryPrimitives.WriteUInt64LittleEndian(payload.Slice(41, 8), connectionId);

        Span<byte> expectedMac = stackalloc byte[32];
        HmacKeccak256.Compute(s_hmacKey, payload, expectedMac);

        if (!CryptographicOperations.FixedTimeEquals(expectedMac, providedMac))
        {
            return false;
        }

        if (difficulty == 0)
        {
            return true; // Skipped / Trivial difficulty
        }

        // 2. Verify the mathematical solution.
        // Puzzle Payload: Nonce (32) | Difficulty (1) | Timestamp (8) | Solution (8) = 49 bytes
        Span<byte> puzzle = stackalloc byte[49];
        nonce.CopyTo(puzzle);
        puzzle[32] = difficulty;
        BinaryPrimitives.WriteInt64LittleEndian(puzzle.Slice(33, 8), timestampTicks);
        BinaryPrimitives.WriteInt64LittleEndian(puzzle.Slice(41, 8), solution);

        Span<byte> hash = stackalloc byte[32];
        Keccak256.HashData(puzzle, hash);

        return ProofOfWorkSolver.HasLeadingZeroBits(hash, difficulty);
    }
}
