<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>SDK</RootNamespace>
		<ServerGarbageCollection>false</ServerGarbageCollection>
		<RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
		<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>

		<Optimize>true</Optimize>
		<TieredCompilation>true</TieredCompilation>
		<AssemblyName>SDK</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Nalix.Observability.Contracts\Nalix.Observability.Contracts.csproj" />
		<ProjectReference Include="..\..\src\Nalix.SDK\Nalix.SDK.csproj" />
		<ProjectReference Include="..\..\src\Nalix.Logging\Nalix.Logging.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Spectre.Console" Version="0.55.2" />
	</ItemGroup>

</Project>
