<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>SecureMultiTransportHelloWorld.Contracts</RootNamespace>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Nalix.Abstractions" Version="14.3.1" />
		<PackageReference Include="Nalix.Codec" Version="14.3.1" />
	</ItemGroup>

</Project>
