// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using System;
using System.Buffers.Binary;
using System.IO;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Nalix.Abstractions.Exceptions;

namespace Nalix.Codec.DataFrames.Chunks;

//┌───────────────────────────────────────────────────────────────────────────┐
//│  Wire format for each chunk(= 1 normal framed packet)                     │
//│                                                                           │
//│  [2 B LE] FramedSocket outer frame length                                 │
//│  payload:                                                                 │
//│    [1 B] Magic        — 0xF0 (validate fragment)                          │
//│    [2 B LE] StreamId     — distinguishes parallel streams                 │
//│    [2 B LE] ChunkIndex   — 0-based index                                  │
//│    [2 B LE] TotalChunks  — known in advance                               │
//│    [1 B] Flags        — bit0 = IsLastChunk                                │
//│    [N B] Chunk body(split automatically)                                  │
//│                                                                           │
//│  Overhead / chunk = 2 B (frame) + 8 B (FragmentHeader) = 10 B             │
//│  PacketFlags.FRAGMENTED is set so the receiver can detect it              │
//└───────────────────────────────────────────────────────────────────────────┘

/// <summary>
/// Fixed-size <b>7-byte</b> header located at the start of the payload for each chunk.
/// <para>
/// <b>Shared contract</b> between SDK (<c>FrameSender</c> / <c>FrameReader</c>)
/// and Server (<c>SocketConnection</c>).
/// Both sides use <see cref="WriteTo"/> when sending and <see cref="ReadFrom"/> when receiving.
/// </para>
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
[method: MethodImpl(MethodImplOptions.AggressiveInlining)]
public readonly struct FragmentHeader(ushort streamId, ushort chunkIndex, ushort totalChunks, bool isLast) : IEquatable<FragmentHeader>
{
    #region Constants

    /// <inheritdoc/>
    public const byte Magic = 0xF0;
    private const byte FlagIsLast = 0b0000_0001;

    /// <summary>
    /// Number of bytes the header occupies on the wire (8 bytes).
    /// </summary>
    public const int WireSize = (sizeof(ushort) * 3) + (sizeof(byte) * 2);

    #endregion Constants

    #region Properties

    /// <summary>
    /// Stream ID — generated by <see cref="FragmentStreamId.Next"/>. Never zero.
    /// </summary>
    public readonly ushort StreamId = streamId;

    /// <summary>
    /// Zero-based index of this chunk in the stream.
    /// </summary>
    public readonly ushort ChunkIndex = chunkIndex;

    /// <summary>
    /// Total number of chunks in the stream.
    /// </summary>
    public readonly ushort TotalChunks = totalChunks;

    /// <summary
    /// >Flags byte — bit 0 = IsLastChunk. Other bits reserved for future use.
    /// </summary>
    public readonly byte Flags = isLast ? FlagIsLast : (byte)0;

    /// <summary>
    /// <see langword="true"/> if this is the last chunk.
    /// </summary>
    public bool IsLast => (Flags & FlagIsLast) != 0;

    #endregion Properties

    #region Constructors

    static FragmentHeader()
    {
        int actual = Unsafe.SizeOf<FragmentHeader>();
        int expected = WireSize - 1;

        if (actual != expected)
        {
            throw new InternalErrorException(
                $"FragmentHeader size mismatch: actual={actual}, expected={expected} (WireSize-1).");
        }
    }

    #endregion Constructors

    #region APIs

    /// <summary>
    /// Write the header to <paramref name="dest"/> (little-endian).
    /// Requires <paramref name="dest"/>.Length >= <see cref="WireSize"/>.
    /// </summary>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="dest"/> is shorter than <see cref="WireSize"/>.</exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void WriteTo(Span<byte> dest)
    {
        dest[0] = Magic;
        BinaryPrimitives.WriteUInt16LittleEndian(dest[1..], StreamId);
        BinaryPrimitives.WriteUInt16LittleEndian(dest[3..], ChunkIndex);
        BinaryPrimitives.WriteUInt16LittleEndian(dest[5..], TotalChunks);
        dest[7] = Flags;
    }

    /// <summary>
    /// Read header from the start of <paramref name="src"/> (little-endian).
    /// Requires <paramref name="src"/>.Length >= <see cref="WireSize"/>.
    /// </summary>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="src"/> is shorter than <see cref="WireSize"/>.</exception>
    /// <exception cref="InvalidDataException">Thrown when the fragment magic marker is invalid.</exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static FragmentHeader ReadFrom(ReadOnlySpan<byte> src)
    {
        if (src[0] != Magic)
        {
            throw new InvalidDataException("Invalid fragment magic");
        }

        return new(
            streamId: BinaryPrimitives.ReadUInt16LittleEndian(src[1..]),
            chunkIndex: BinaryPrimitives.ReadUInt16LittleEndian(src[3..]),
            totalChunks: BinaryPrimitives.ReadUInt16LittleEndian(src[5..]),
            isLast: (src[7] & FlagIsLast) != 0);
    }

    // ── Equality ─────────────────────────────────────────────────────────────

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public bool Equals(FragmentHeader other)
        => StreamId == other.StreamId && ChunkIndex == other.ChunkIndex
        && TotalChunks == other.TotalChunks && Flags == other.Flags;

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public override bool Equals(object? obj) => obj is FragmentHeader h && this.Equals(h);

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public override int GetHashCode() => HashCode.Combine(StreamId, ChunkIndex, TotalChunks, Flags);

    /// <inheritdoc/>
    public override string ToString() => $"Chunk(stream={StreamId}, {ChunkIndex}/{TotalChunks - 1}, last={this.IsLast})";

    /// <inheritdoc/>
    public static bool operator ==(FragmentHeader left, FragmentHeader right) => left.Equals(right);

    /// <inheritdoc/>
    public static bool operator !=(FragmentHeader left, FragmentHeader right) => !(left == right);

    #endregion APIs
}
