// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using Microsoft.CodeAnalysis;

namespace Nalix.Analyzers.Generators.Internal;

/// <summary>
/// Provides helper methods for generated source namespaces.
/// </summary>
internal static class SourceGenNamespaces
{
    private const string AutoGeneratedSuffix = "AutoGenerated";

    /// <summary>
    /// Gets the generated namespace for the specified type.
    /// </summary>
    /// <param name="type">The target type symbol.</param>
    /// <returns>
    /// The root namespace with <c>.AutoGenerated</c> appended,
    /// or <c>AutoGenerated</c> when the type is declared in the global namespace.
    /// </returns>
    public static string Get(ITypeSymbol type) => $"{type.ContainingAssembly.Name}.{AutoGeneratedSuffix}";
}
