<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>UdpLoadTester</RootNamespace>
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
		<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>

		<Optimize>true</Optimize>
		<TieredCompilation>true</TieredCompilation>
		<AssemblyName>UdpLoadTester</AssemblyName>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Nalix.SDK\Nalix.SDK.csproj" />
		<ProjectReference Include="..\..\extensions\Nalix.Logging\Nalix.Logging.csproj" />
	</ItemGroup>

</Project>
