// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Nalix.Generators;

/// <summary>
/// Generates packet registry catalogs for packet types declared in the current
/// compilation.
/// </summary>
[Generator]
public sealed class PacketRegistryGenerator : IIncrementalGenerator
{
    private const string IPacketMetadataName = "Nalix.Abstractions.Networking.Packets.IPacket";

    /// <summary>
    /// Registers the incremental source-generation pipeline.
    /// </summary>
    /// <param name="context">The Roslyn incremental generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol?> packets = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => GetPacketType(ctx))
            .Where(static symbol => symbol is not null);

        IncrementalValueProvider<(Compilation Compilation, System.Collections.Immutable.ImmutableArray<INamedTypeSymbol?> Packets)> collected =
            context.CompilationProvider.Combine(packets.Collect());

        context.RegisterSourceOutput(collected, static (spc, source) => Execute(source.Compilation, source.Packets, spc));
    }

    private static INamedTypeSymbol? GetPacketType(GeneratorSyntaxContext context)
    {
        if (context.Node is not TypeDeclarationSyntax typeDecl)
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(typeDecl) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.IsAbstract || symbol.TypeKind == TypeKind.Interface || symbol.IsGenericType)
        {
            return null;
        }

        return ImplementsInterface(symbol, IPacketMetadataName) ? symbol : null;
    }

    private static bool ImplementsInterface(INamedTypeSymbol symbol, string metadataName) =>
        symbol.AllInterfaces.Any(i => i.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::" + metadataName);

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>")]
    private static void Execute(
        Compilation compilation,
        System.Collections.Immutable.ImmutableArray<INamedTypeSymbol?> packets,
        SourceProductionContext context)
    {
        HashSet<string> seen = new();
        List<INamedTypeSymbol> distinctPackets = [.. packets
            .Where(static p => p is not null)
            .Select(static p => p!)
            .Where(p => seen.Add(p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
            .OrderBy(static p => p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))];

        StringBuilder sb = new();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#pragma warning disable CS1591");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using System.Collections.Generic;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("namespace Nalix.Abstractions.Networking.Packets;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("internal static class GeneratedPacketManifest");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    public static IReadOnlyList<KeyValuePair<uint, PacketDeserializer>> GetDeserializers()");
        _ = sb.AppendLine("        => s_deserializers;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    public static IReadOnlyList<KeyValuePair<uint, string>> GetNames()");
        _ = sb.AppendLine("        => s_names;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private static readonly KeyValuePair<uint, PacketDeserializer>[] s_deserializers =");
        _ = sb.AppendLine("    [");

        foreach (INamedTypeSymbol packet in distinctPackets)
        {
            string typeName = packet.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string fullName = packet.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
            string key = Compute(fullName).ToString(System.Globalization.CultureInfo.InvariantCulture);

            _ = sb.AppendLine($"        new({key}u, static raw => {typeName}.Deserialize(raw)),");
        }

        _ = sb.AppendLine("    ];");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private static readonly KeyValuePair<uint, string>[] s_names =");
        _ = sb.AppendLine("    [");

        foreach (INamedTypeSymbol packet in distinctPackets)
        {
            string fullName = packet.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
            string key = Compute(fullName).ToString(System.Globalization.CultureInfo.InvariantCulture);

            _ = sb.AppendLine($"        new({key}u, \"{Escape(fullName)}\"),");
        }

        _ = sb.AppendLine("    ];");
        _ = sb.AppendLine("}");

        context.AddSource("Nalix_Abstractions_GeneratedPacketManifest.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static uint Compute(string name)
    {
        const uint Offset = 2166136261u;
        const uint Prime = 16777619u;

        uint hash = Offset;
        byte[] bytes = Encoding.UTF8.GetBytes(name);
        foreach (byte b in bytes)
        {
            hash ^= b;
            hash *= Prime;
        }

        return hash;
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
