// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Nalix.AutoGenerated.Internal;

internal static class Fnv1a
{
    private const uint Prime = 16777619u;
    private const uint OffsetBasis = 2166136261u;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint Compute(ReadOnlySpan<char> input)
    {
        uint hash = OffsetBasis;

        ref char r0 = ref MemoryMarshal.GetReference(input);

        int i = 0;
        int length = input.Length;

        while (i <= length - 4)
        {
            hash = (hash ^ Unsafe.Add(ref r0, i)) * Prime;
            hash = (hash ^ Unsafe.Add(ref r0, i + 1)) * Prime;
            hash = (hash ^ Unsafe.Add(ref r0, i + 2)) * Prime;
            hash = (hash ^ Unsafe.Add(ref r0, i + 3)) * Prime;

            i += 4;
        }

        while (i < length)
        {
            hash = (hash ^ Unsafe.Add(ref r0, i)) * Prime;
            i++;
        }

        return hash;
    }
}
