using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace Nalix.AutoGenerated.Internal;

internal static class GeneratorHelper
{
    public const string GeneratedFormatterNamespace = "Nalix.AutoGenerated.Formatter";
    public const string GenerateFormatterAttributeName = "GenerateFormatterAttribute";

    public const string SerializeOrderAttributeName = "SerializeOrderAttribute";
    public const string SerializeIgnoreAttributeName = "SerializeIgnoreAttribute";
    public const string SerializeHeaderAttributeName = "SerializeHeaderAttribute";
    public const string SerializeDynamicSizeAttributeName = "SerializeDynamicSizeAttribute";

    public static List<ISymbol> GetOrderedMembers(ITypeSymbol type)
    {
        List<ISymbol> allMembers = new(16);
        ITypeSymbol? currentType = type;

        // Walk inheritance chain (supports FrameBase / PacketBase patterns)
        while (currentType is not null && currentType.SpecialType == SpecialType.None)
        {
            List<ISymbol> levelMembers = new();
            ImmutableArray<ISymbol> members = currentType.GetMembers();

            // First pass: add all members that have explicit serialization attributes
            foreach (ISymbol member in members)
            {
                if (member is not (IPropertySymbol or IFieldSymbol) || member.IsStatic)
                {
                    continue;
                }

                // For properties, we check if they have the attribute or if they wrap an attributed field.
                // For fields, we only check the field itself.
                AttributeData? headerAttr = GetAttribute(member, SerializeHeaderAttributeName);
                AttributeData? orderAttr = GetAttribute(member, SerializeOrderAttributeName);
                AttributeData? dynamicAttr = GetAttribute(member, SerializeDynamicSizeAttributeName);

                if (headerAttr is not null || orderAttr is not null || dynamicAttr is not null)
                {
                    // If this is a private field, and there is a public property wrapping it that ALSO has an attribute,
                    // we skip the field to avoid double counting.
                    if (member is IFieldSymbol field && field.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
                    {
                        bool hasPublicWrapperWithAttribute = members.OfType<IPropertySymbol>().Any(p =>
                            SymbolEqualityComparer.Default.Equals(p.Type, field.Type) &&
                            (GetAttribute(p, SerializeOrderAttributeName) is not null ||
                             GetAttribute(p, SerializeHeaderAttributeName) is not null ||
                             GetAttribute(p, SerializeDynamicSizeAttributeName) is not null));

                        if (hasPublicWrapperWithAttribute)
                        {
                            continue;
                        }
                    }

                    levelMembers.Add(member);
                    continue;
                }

                // If no explicit attribute, check if we should include it by default
                bool isIgnored = member.GetAttributes().Any(static a => a.AttributeClass?.Name == SerializeIgnoreAttributeName);
                if (isIgnored)
                {
                    continue;
                }

                if (member.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal)
                {
                    // Check if this property is a wrapper for a field that already has an attribute
                    if (member is IPropertySymbol prop)
                    {
                        bool wrapperForAttributed = prop.ContainingType.GetMembers()
                            .OfType<IFieldSymbol>()
                            .Any(f => SymbolEqualityComparer.Default.Equals(f.Type, prop.Type) &&
                                     (GetAttribute(f, SerializeOrderAttributeName) is not null ||
                                      GetAttribute(f, SerializeHeaderAttributeName) is not null ||
                                      GetAttribute(f, SerializeDynamicSizeAttributeName) is not null));

                        if (wrapperForAttributed)
                        {
                            continue;
                        }
                    }

                    levelMembers.Add(member);
                }
            }

            allMembers.InsertRange(0, levelMembers);
            currentType = currentType.BaseType;
        }

        // Deduplicate members by name across levels (Derived hides Base)
        // Actually, for serialization we want all levels, but if a member is FOUND in multiple levels
        // (e.g. shadowed), we only want one.
        // But wait! FrameBase members are shared.

        // Separate + order headers first, then payload
        IOrderedEnumerable<ISymbol> headers = allMembers
            .Where(m => GetAttribute(m, SerializeHeaderAttributeName) is not null)
            .OrderBy(m => (int)GetAttribute(m, SerializeHeaderAttributeName)!.ConstructorArguments[0].Value!);

        IEnumerable<ISymbol> payload = allMembers
            .Where(m => GetAttribute(m, SerializeHeaderAttributeName) is null);

        IOrderedEnumerable<ISymbol> orderedPayload = payload
            .OrderBy(m =>
            {
                AttributeData? attr = GetAttribute(m, SerializeOrderAttributeName);
                return attr is not null ? (int)attr.ConstructorArguments[0].Value! : int.MaxValue;
            });

        return [.. headers, .. orderedPayload];
    }

    private static AttributeData? GetAttribute(ISymbol member, string attrName)
    {
        AttributeData? attr = member.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == attrName);
        if (attr is not null)
        {
            return attr;
        }

        if (member is IPropertySymbol prop)
        {
            // Try to find the attribute on a backing field
            return prop.ContainingType.GetMembers()
                .OfType<IFieldSymbol>()
                .FirstOrDefault(f =>
                    SymbolEqualityComparer.Default.Equals(f.Type, prop.Type) &&
                    f.GetAttributes().Any(a => a.AttributeClass?.Name == attrName))
                ?.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == attrName);
        }
        return null;
    }
}
