// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Nalix.AutoGenerated.Internal;

internal static class Hashing
{
    private const uint FnvPrime = 16777619u;
    private const uint FnvOffsetBasis = 2166136261u;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint ComputeFnv1a(ReadOnlySpan<char> input)
    {
        uint hash = FnvOffsetBasis;
        int length = input.Length;

        ref char searchSpace = ref MemoryMarshal.GetReference(input);
        int i = 0;

        if (i <= length - 4)
        {
            hash = (hash ^ Unsafe.Add(ref searchSpace, i)) * FnvPrime;
            hash = (hash ^ Unsafe.Add(ref searchSpace, i + 1)) * FnvPrime;
            hash = (hash ^ Unsafe.Add(ref searchSpace, i + 2)) * FnvPrime;
            hash = (hash ^ Unsafe.Add(ref searchSpace, i + 3)) * FnvPrime;
            i += 4;
        }

        while (i < length)
        {
            hash = (hash ^ Unsafe.Add(ref searchSpace, i)) * FnvPrime;
            i++;
        }

        return hash;
    }
}
