// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

namespace Nalix.AutoGenerated.Internal;

internal class KnownNames
{
    // Namespace
    public const string CodecMemoryNamespace = "Nalix.Environment.Memory";
    public const string AbstractionsNamespace = "Nalix.Abstractions";
    public const string PacketBaseNamespace = "Nalix.Codec.DataFrames";
    public const string CodecExtensionsNamespace = "Nalix.Codec.Extensions";
    public const string LiteSerializerNamespace = "Nalix.Codec.Serialization";
    public const string GeneratedFormatterNamespace = "Nalix.AutoGenerated.Formatter";
    public const string GenerateFormatterAttributeName = "GenerateFormatterAttribute";
    public const string ExceptionsAbstractionsNamespace = "Nalix.Abstractions.Exceptions";
    public const string PacketAbstractionsNamespace = "Nalix.Abstractions.Networking.Packets";
    public const string SerializationAbstractionsNamespace = "Nalix.Abstractions.Serialization";
    public const string ConfigurationBindingNamespace = "Nalix.Environment.Configuration.Binding";
    public const string PacketAttributeMetadataName = "Nalix.Abstractions.Networking.Packets.PacketAttribute";

    // Types
    public const string IniCommentShort = "IniComment";
    public const string ConfigurationLoader = "ConfigurationLoader";

    public const string PacketBaseName = "PacketBase";
    public const string IPacketInterfaceName = "IPacket";

    public const string IFixedSizeSerializableName = "IFixedSizeSerializable";

    public const string LiteSerializerName = "LiteSerializer";

    // Common Types
    public const string GuidName = "Guid";
    public const string TimeSpanName = "TimeSpan";
    public const string TimeOnlyName = "TimeOnly";
    public const string DateOnlyName = "DateOnly";
    public const string DateTimeOffsetName = "DateTimeOffset";

    // Attributes
    public const string SkipCleanName = "SkipClean";
    public const string SerializeIgnoreShortName = "SerializeIgnore";
    public const string SerializeOrderAttributeName = "SerializeOrderAttribute";
    public const string SerializeIgnoreAttributeName = "SerializeIgnoreAttribute";
    public const string SerializeHeaderAttributeName = "SerializeHeaderAttribute";
    public const string SerializeDynamicSizeAttributeName = "SerializeDynamicSizeAttribute";

    public const string PacketSchemaName = "PacketSchema";
    public const string PacketRegistryName = "PacketRegistry";
    public const string PacketDispatchName = "PacketDispatch";

    public const string IniCommentAttribute = "IniCommentAttribute";
    public const string ConfiguredIgnoreAttribute = "ConfiguredIgnoreAttribute";

}
