// Copyright (c) 2026 PPN Corporation. All rights reserved.
// Licensed under the Apache License, Version 2.0.

namespace Nalix.AutoGenerated.Internal;

internal class KnownNames
{
    // Namespace
    public const string PacketBaseNamespace = "Nalix.Codec.DataFrames";
    public const string GeneratedFormatterNamespace = "Nalix.AutoGenerated.Formatter";
    public const string GenerateFormatterAttributeName = "GenerateFormatterAttribute";
    public const string ConfigurationBindingNamespace = "Nalix.Environment.Configuration.Binding";
    public const string PacketAttributeMetadataName = "Nalix.Abstractions.Networking.Packets.PacketAttribute";

    // Types
    public const string IniCommentShort = "IniComment";
    public const string ConfigurationLoader = "ConfigurationLoader";

    public const string PacketBaseName = "PacketBase";
    public const string IPacketInterfaceName = "IPacket";

    public const string IFixedSizeSerializableName = "IFixedSizeSerializable";

    // Attributes
    public const string SerializeOrderAttributeName = "SerializeOrderAttribute";
    public const string SerializeIgnoreAttributeName = "SerializeIgnoreAttribute";
    public const string SerializeHeaderAttributeName = "SerializeHeaderAttribute";
    public const string SerializeDynamicSizeAttributeName = "SerializeDynamicSizeAttribute";

    public const string IniCommentAttribute = "IniCommentAttribute";
    public const string ConfiguredIgnoreAttribute = "ConfiguredIgnoreAttribute";

}
