// <auto-generated>
//     This code was generated by Nalix.Tools.Protogen.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

export class BinaryWriter {
    private buffer: Uint8Array;
    private view: DataView;
    private offset: number = 0;

    constructor(initialCapacity: number = 256) {
        this.buffer = new Uint8Array(initialCapacity);
        this.view = new DataView(this.buffer.buffer);
    }

    public getBuffer(): Uint8Array {
        return this.buffer.subarray(0, this.offset);
    }

    private ensureCapacity(size: number) {
        if (this.offset + size > this.buffer.length) {
            const newBuffer = new Uint8Array(Math.max(this.buffer.length * 2, this.offset + size));
            newBuffer.set(this.buffer);
            this.buffer = newBuffer;
            this.view = new DataView(this.buffer.buffer);
        }
    }

    public writeByte(value: number) {
        this.ensureCapacity(1);
        this.view.setUint8(this.offset, value);
        this.offset += 1;
    }

    public writeSByte(value: number) {
        this.ensureCapacity(1);
        this.view.setInt8(this.offset, value);
        this.offset += 1;
    }

    public writeInt16(value: number) {
        this.ensureCapacity(2);
        this.view.setInt16(this.offset, value, true);
        this.offset += 2;
    }

    public writeUint16(value: number) {
        this.ensureCapacity(2);
        this.view.setUint16(this.offset, value, true);
        this.offset += 2;
    }

    public writeInt32(value: number) {
        this.ensureCapacity(4);
        this.view.setInt32(this.offset, value, true);
        this.offset += 4;
    }

    public writeUint32(value: number) {
        this.ensureCapacity(4);
        this.view.setUint32(this.offset, value, true);
        this.offset += 4;
    }

    public writeInt64(value: bigint) {
        this.ensureCapacity(8);
        this.view.setBigInt64(this.offset, value, true);
        this.offset += 8;
    }

    public writeUint64(value: bigint) {
        this.ensureCapacity(8);
        this.view.setBigUint64(this.offset, value, true);
        this.offset += 8;
    }

    public writeSingle(value: number) {
        this.ensureCapacity(4);
        this.view.setFloat32(this.offset, value, true);
        this.offset += 4;
    }

    public writeDouble(value: number) {
        this.ensureCapacity(8);
        this.view.setFloat64(this.offset, value, true);
        this.offset += 8;
    }

    public writeBoolean(value: boolean) {
        this.writeByte(value ? 1 : 0);
    }

    public writeString(value: string | null) {
        if (value === null) {
            this.writeInt32(-1);
            return;
        }
        const encoder = new TextEncoder();
        const encoded = encoder.encode(value);
        this.writeInt32(encoded.length);
        this.ensureCapacity(encoded.length);
        this.buffer.set(encoded, this.offset);
        this.offset += encoded.length;
    }

    public writeGuid(value: string) {
        // Guid is 16 bytes
        // Expected format: "00000000-0000-0000-0000-000000000000"
        const hex = value.replace(/-/g, '');
        this.ensureCapacity(16);
        for (let i = 0; i < 16; i++) {
            this.view.setUint8(this.offset + i, parseInt(hex.substring(i * 2, i * 2 + 2), 16));
        }
        this.offset += 16;
    }

    public writeSnowflake(value: bigint) {
        this.writeUint64(value);
    }

    public writeUint56(value: bigint) {
        this.ensureCapacity(7);
        let temp = value;
        for (let i = 0; i < 7; i++) {
            this.view.setUint8(this.offset + i, Number(temp & 0xFFn));
            temp >>= 8n;
        }
        this.offset += 7;
    }

    public writeBytes32(value: Uint8Array) {
        this.ensureCapacity(32);
        this.buffer.set(value.subarray(0, 32), this.offset);
        this.offset += 32;
    }

    public writeBytes(value: Uint8Array) {
        this.ensureCapacity(value.length);
        this.buffer.set(value, this.offset);
        this.offset += value.length;
    }

    public writeDecimal(value: number) {
        this.ensureCapacity(16);
        this.view.setFloat64(this.offset + 8, value, true);
        this.offset += 16;
    }
}

export class BinaryReader {
    private buffer: Uint8Array;
    private view: DataView;
    private offset: number = 0;

    constructor(buffer: Uint8Array) {
        this.buffer = buffer;
        this.view = new DataView(this.buffer.buffer, this.buffer.byteOffset, this.buffer.byteLength);
    }

    public readByte(): number {
        const val = this.view.getUint8(this.offset);
        this.offset += 1;
        return val;
    }

    public readSByte(): number {
        const val = this.view.getInt8(this.offset);
        this.offset += 1;
        return val;
    }

    public readInt16(): number {
        const val = this.view.getInt16(this.offset, true);
        this.offset += 2;
        return val;
    }

    public readUint16(): number {
        const val = this.view.getUint16(this.offset, true);
        this.offset += 2;
        return val;
    }

    public readInt32(): number {
        const val = this.view.getInt32(this.offset, true);
        this.offset += 4;
        return val;
    }

    public readUint32(): number {
        const val = this.view.getUint32(this.offset, true);
        this.offset += 4;
        return val;
    }

    public readInt64(): bigint {
        const val = this.view.getBigInt64(this.offset, true);
        this.offset += 8;
        return val;
    }

    public readUint64(): bigint {
        const val = this.view.getBigUint64(this.offset, true);
        this.offset += 8;
        return val;
    }

    public readSingle(): number {
        const val = this.view.getFloat32(this.offset, true);
        this.offset += 4;
        return val;
    }

    public readDouble(): number {
        const val = this.view.getFloat64(this.offset, true);
        this.offset += 8;
        return val;
    }

    public readBoolean(): boolean {
        return this.readByte() !== 0;
    }

    public readString(): string | null {
        const length = this.readInt32();
        if (length === -1) return null;
        
        const decoder = new TextDecoder();
        const str = decoder.decode(this.buffer.subarray(this.offset, this.offset + length));
        this.offset += length;
        return str;
    }

    public readGuid(): string {
        let hex = '';
        for (let i = 0; i < 16; i++) {
            hex += this.view.getUint8(this.offset + i).toString(16).padStart(2, '0');
        }
        this.offset += 16;
        return `${hex.substring(0,8)}-${hex.substring(8,12)}-${hex.substring(12,16)}-${hex.substring(16,20)}-${hex.substring(20)}`;
    }

    public readSnowflake(): bigint {
        return this.readUint64();
    }

    public readUint56(): bigint {
        let val = 0n;
        for (let i = 0; i < 7; i++) {
            val |= BigInt(this.view.getUint8(this.offset + i)) << BigInt(i * 8);
        }
        this.offset += 7;
        return val;
    }

    public readBytes32(): Uint8Array {
        const arr = new Uint8Array(32);
        arr.set(this.buffer.subarray(this.offset, this.offset + 32));
        this.offset += 32;
        return arr;
    }

    public readBytes(length: number): Uint8Array {
        const arr = new Uint8Array(length);
        arr.set(this.buffer.subarray(this.offset, this.offset + length));
        this.offset += length;
        return arr;
    }

    public readDecimal(): number {
        this.offset += 8;
        const val = this.view.getFloat64(this.offset, true);
        this.offset += 8;
        return val;
    }
}
