<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ImplicitUsings>enable</ImplicitUsings>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>Nalix.Observability.Contracts</RootNamespace>
		<OutputType>Library</OutputType>
		<AssemblyName>Nalix.Observability.Contracts</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Nalix.Abstractions\Nalix.Abstractions.csproj" />
		<ProjectReference Include="..\..\src\Nalix.Codec\Nalix.Codec.csproj" />
		<ProjectReference Include="..\..\src\Nalix.Analyzers.Generators\Nalix.Analyzers.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=netstandard2.0" AdditionalProperties="PublishAot=false;PublishTrimmed=false;IsTrimmable=false;IsAotCompatible=false" />
	</ItemGroup>

</Project>
