<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  
	<PropertyGroup>
		<!-- Packing -->
		<IsPackable>true</IsPackable>
		<OutputType>Library</OutputType>
		<Deterministic>true</Deterministic>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<!-- Package metadata -->
		<Product>Nalix® .NET</Product>
		<Authors>PPN Corporation</Authors>
		<Company>PPN Corporation</Company>
		<RepositoryType>git</RepositoryType>
		<NeutralLanguage>en-US</NeutralLanguage>

		<PackageIcon>nalix.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<RepositoryUrl>https://github.com/ppn-systems/Nalix</RepositoryUrl>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageProjectUrl>https://github.com/ppn-systems/Nalix</PackageProjectUrl>
		<Copyright>Copyright (c) 2025-2026 PPN Corporation. All rights reserved.</Copyright>
	</PropertyGroup>

	<PropertyGroup Label="Assembly Properties">
		<DebugSymbols>true</DebugSymbols>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<ProduceReferenceAssembly>True</ProduceReferenceAssembly>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
  
</Project>
