<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>

		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<OutputType>Library</OutputType>
		<IsTrimmable>true</IsTrimmable>
		<TrimMode>partial</TrimMode>
		<IsAotCompatible>true</IsAotCompatible>
		<Deterministic>true</Deterministic>

		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

	</PropertyGroup>

	<Import Project="..\..\src\Nalix.Build.props" />

	<ItemGroup>
		<ProjectReference Include="..\..\src\Nalix.Framework\Nalix.Framework.csproj" />
		<ProjectReference Include="..\..\src\Nalix.Abstractions\Nalix.Abstractions.csproj" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
	</ItemGroup>
</Project>
