using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using Nalix.Tools.Protogen.Domain.Interfaces;
using Nalix.Tools.Protogen.Domain.Models;

namespace Nalix.Tools.Protogen.Generators.TypeScript;

public class TypeScriptGenerator : ICodeGenerator
{
    public string LanguageName => "TypeScript";

    public Dictionary<string, string> Generate(IEnumerable<PacketDefinition> packets)
    {
        var files = new Dictionary<string, string>();

        // We load the protocol directly. We assume it's copied or read from disk.
        // For simplicity in this CLI, we will just embed the template string in a C# class 
        // to avoid missing file errors when users distribute the tool.
        files.Add("BinaryProtocol.ts", BinaryProtocolTemplate.Content);

        foreach (var packet in packets)
        {
            string tsCode = GeneratePacket(packet);
            files.Add($"{packet.Name}.ts", tsCode);
        }

        return files;
    }

    private string GeneratePacket(PacketDefinition packet)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by Nalix.Tools.Protogen.");
        sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("import { BinaryReader, BinaryWriter } from './BinaryProtocol';");
        sb.AppendLine();
        sb.AppendLine("/**");
        sb.AppendLine($" * @description Auto-generated from {packet.Namespace}.{packet.Name}");
        sb.AppendLine(" */");
        sb.AppendLine($"export class {packet.Name} {{");
        sb.AppendLine($"    public static readonly MAGIC: number = 0x{packet.MagicNumber:X8};");
        if (packet.OpCode.HasValue)
        {
            sb.AppendLine($"    public static readonly OPCODE: number = {packet.OpCode.Value};");
        }
        sb.AppendLine();

        // Protocol Headers
        sb.AppendLine("    // --- Fixed Header ---");
        if (packet.OpCode.HasValue)
        {
            sb.AppendLine($"    public OpCode: number = {packet.OpCode.Value};");
        }
        else
        {
            sb.AppendLine("    public OpCode: number = 0;");
        }
        sb.AppendLine("    public Flags: number = 0;");
        sb.AppendLine("    public Priority: number = 0;");
        sb.AppendLine("    public SequenceId: number = 0;");
        sb.AppendLine("    // --------------------");
        sb.AppendLine();

        // Properties
        foreach (var prop in packet.Properties)
        {
            string tsType = TypeScriptTypeResolver.GetTsType(prop);
            sb.AppendLine($"    public {prop.Name}!: {tsType};");
        }
        sb.AppendLine();

        // Serialize
        sb.AppendLine("    public serialize(writer: BinaryWriter): void {");
        sb.AppendLine($"        writer.writeUint32({packet.Name}.MAGIC);");
        sb.AppendLine("        writer.writeUint16(this.OpCode);");
        sb.AppendLine("        writer.writeByte(this.Flags);");
        sb.AppendLine("        writer.writeByte(this.Priority);");
        sb.AppendLine("        writer.writeUint16(this.SequenceId);");
        sb.AppendLine();

        foreach (var prop in packet.Properties)
        {
            WriteSerializeLogic(sb, prop, "this." + prop.Name, "        ");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // Deserialize
        sb.AppendLine($"    public static deserialize(reader: BinaryReader): {packet.Name} {{");
        sb.AppendLine($"        const magic = reader.readUint32();");
        sb.AppendLine($"        if (magic !== {packet.Name}.MAGIC) throw new Error(`Invalid Magic Number: expected 0x${{{packet.Name}.MAGIC.toString(16)}}, got 0x${{magic.toString(16)}}`);");
        sb.AppendLine($"        const packet = new {packet.Name}();");
        sb.AppendLine("        packet.OpCode = reader.readUint16();");
        sb.AppendLine("        packet.Flags = reader.readByte();");
        sb.AppendLine("        packet.Priority = reader.readByte();");
        sb.AppendLine("        packet.SequenceId = reader.readUint16();");
        sb.AppendLine();

        foreach (var prop in packet.Properties)
        {
            WriteDeserializeLogic(sb, prop, "packet." + prop.Name, "        ");
        }
        sb.AppendLine("        return packet;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private void WriteSerializeLogic(StringBuilder sb, PropertyDefinition prop, string accessor, string indent)
    {
        if (prop.IsNullable && prop.Kind != TypeKind.Array && prop.Kind != TypeKind.List && prop.Kind != TypeKind.Dictionary)
        {
            sb.AppendLine($"{indent}if ({accessor} === null) {{");
            sb.AppendLine($"{indent}    writer.writeByte(0);");
            sb.AppendLine($"{indent}}} else {{");
            sb.AppendLine($"{indent}    writer.writeByte(1);");
            indent += "    ";
        }

        switch (prop.Kind)
        {
            case TypeKind.Primitive:
                string method = TypeScriptTypeResolver.GetWriterMethodForPrimitive(prop.CSharpType);
                sb.AppendLine($"{indent}writer.{method}({accessor});");
                break;
            case TypeKind.String:
                sb.AppendLine($"{indent}writer.writeString({accessor});");
                break;
            case TypeKind.DateTime:
                sb.AppendLine($"{indent}writer.writeInt64({accessor});");
                break;
            case TypeKind.Guid:
                sb.AppendLine($"{indent}writer.writeGuid({accessor});");
                break;
            case TypeKind.Snowflake:
                sb.AppendLine($"{indent}writer.writeSnowflake({accessor});");
                break;
            case TypeKind.Bytes32:
                sb.AppendLine($"{indent}writer.writeBytes32({accessor});");
                break;
            case TypeKind.Array:
            case TypeKind.List:
            case TypeKind.Stack:
            case TypeKind.Queue:
                sb.AppendLine($"{indent}writer.writeInt32({accessor}.length);");
                sb.AppendLine($"{indent}for (let i = 0; i < {accessor}.length; i++) {{");
                WriteCollectionItemSerialize(sb, prop.ElementType!, $"{accessor}[i]", indent + "    ");
                sb.AppendLine($"{indent}}}");
                break;
            case TypeKind.HashSet:
                sb.AppendLine($"{indent}writer.writeInt32({accessor}.size);");
                sb.AppendLine($"{indent}for (const item of {accessor}) {{");
                WriteCollectionItemSerialize(sb, prop.ElementType!, "item", indent + "    ");
                sb.AppendLine($"{indent}}}");
                break;
            case TypeKind.Dictionary:
                sb.AppendLine($"{indent}writer.writeInt32({accessor}.size);");
                sb.AppendLine($"{indent}for (const [key, val] of {accessor}.entries()) {{");
                WriteCollectionItemSerialize(sb, prop.KeyType!, "key", indent + "    ");
                WriteCollectionItemSerialize(sb, prop.ValueType!, "val", indent + "    ");
                sb.AppendLine($"{indent}}}");
                break;
            case TypeKind.Memory:
                sb.AppendLine($"{indent}writer.writeInt32({accessor}.length);");
                sb.AppendLine($"{indent}writer.writeBytes({accessor});");
                break;
            case TypeKind.ValueTuple:
                for (int i = 0; i < prop.TupleElements.Count; i++)
                {
                    WriteCollectionItemSerialize(sb, prop.TupleElements[i], $"{accessor}[{i}]", indent);
                }
                break;
            case TypeKind.NestedPacket:
                sb.AppendLine($"{indent}{accessor}.serialize(writer);");
                break;
        }

        if (prop.IsNullable && prop.Kind != TypeKind.Array && prop.Kind != TypeKind.List && prop.Kind != TypeKind.Dictionary)
        {
            indent = indent.Substring(0, indent.Length - 4);
            sb.AppendLine($"{indent}}}");
        }
    }

    private void WriteCollectionItemSerialize(StringBuilder sb, string csharpType, string accessor, string indent)
    {
        string writeMethod = TypeScriptTypeResolver.GetWriterMethodForPrimitive(csharpType);
        if (writeMethod != "unknown")
        {
            sb.AppendLine($"{indent}writer.{writeMethod}({accessor});");
        }
        else
        {
            sb.AppendLine($"{indent}{accessor}.serialize(writer);");
        }
    }

    private void WriteDeserializeLogic(StringBuilder sb, PropertyDefinition prop, string accessor, string indent)
    {
        if (prop.IsNullable && prop.Kind != TypeKind.Array && prop.Kind != TypeKind.List && prop.Kind != TypeKind.Dictionary)
        {
            sb.AppendLine($"{indent}if (reader.readByte() === 0) {{");
            sb.AppendLine($"{indent}    {accessor} = null;");
            sb.AppendLine($"{indent}}} else {{");
            indent += "    ";
        }

        switch (prop.Kind)
        {
            case TypeKind.Primitive:
                string method = TypeScriptTypeResolver.GetReaderMethodForPrimitive(prop.CSharpType);
                sb.AppendLine($"{indent}{accessor} = reader.{method}();");
                break;
            case TypeKind.String:
                sb.AppendLine($"{indent}{accessor} = reader.readString();");
                break;
            case TypeKind.DateTime:
                sb.AppendLine($"{indent}{accessor} = reader.readInt64();");
                break;
            case TypeKind.Guid:
                sb.AppendLine($"{indent}{accessor} = reader.readGuid();");
                break;
            case TypeKind.Snowflake:
                sb.AppendLine($"{indent}{accessor} = reader.readSnowflake();");
                break;
            case TypeKind.Bytes32:
                sb.AppendLine($"{indent}{accessor} = reader.readBytes32();");
                break;
            case TypeKind.Array:
            case TypeKind.List:
            case TypeKind.Stack:
            case TypeKind.Queue:
                sb.AppendLine($"{indent}const count_{prop.Name} = reader.readInt32();");
                sb.AppendLine($"{indent}{accessor} = [];");
                sb.AppendLine($"{indent}for (let i = 0; i < count_{prop.Name}; i++) {{");
                WriteItemRead(sb, prop.ElementType!, "item", indent + "    ");
                sb.AppendLine($"{indent}    {accessor}.push(item);");
                sb.AppendLine($"{indent}}}");
                break;
            case TypeKind.HashSet:
                sb.AppendLine($"{indent}const count_{prop.Name} = reader.readInt32();");
                sb.AppendLine($"{indent}{accessor} = new Set();");
                sb.AppendLine($"{indent}for (let i = 0; i < count_{prop.Name}; i++) {{");
                WriteItemRead(sb, prop.ElementType!, "item", indent + "    ");
                sb.AppendLine($"{indent}    {accessor}.add(item);");
                sb.AppendLine($"{indent}}}");
                break;
            case TypeKind.Dictionary:
                sb.AppendLine($"{indent}const count_{prop.Name} = reader.readInt32();");
                sb.AppendLine($"{indent}{accessor} = new Map();");
                sb.AppendLine($"{indent}for (let i = 0; i < count_{prop.Name}; i++) {{");
                WriteItemRead(sb, prop.KeyType!, "key", indent + "    ");
                WriteItemRead(sb, prop.ValueType!, "val", indent + "    ");
                sb.AppendLine($"{indent}    {accessor}.set(key, val);");
                sb.AppendLine($"{indent}}}");
                break;
            case TypeKind.Memory:
                sb.AppendLine($"{indent}const count_{prop.Name} = reader.readInt32();");
                sb.AppendLine($"{indent}{accessor} = reader.readBytes(count_{prop.Name});");
                break;
            case TypeKind.ValueTuple:
                sb.AppendLine($"{indent}{accessor} = [");
                for (int i = 0; i < prop.TupleElements.Count; i++)
                {
                    string elemType = prop.TupleElements[i];
                    string itemReadMethod = TypeScriptTypeResolver.GetReaderMethodForPrimitive(elemType);
                    if (itemReadMethod != "unknown")
                        sb.AppendLine($"{indent}    reader.{itemReadMethod}(),");
                    else
                        sb.AppendLine($"{indent}    {elemType}.deserialize(reader),");
                }
                sb.AppendLine($"{indent}];");
                break;
            case TypeKind.NestedPacket:
                sb.AppendLine($"{indent}{accessor} = {prop.CSharpType.Split('.')[^1]}.deserialize(reader);");
                break;
        }

        if (prop.IsNullable && prop.Kind != TypeKind.Array && prop.Kind != TypeKind.List && prop.Kind != TypeKind.Dictionary)
        {
            indent = indent.Substring(0, indent.Length - 4);
            sb.AppendLine($"{indent}}}");
        }
    }

    private void WriteItemRead(StringBuilder sb, string csharpType, string variableName, string indent)
    {
        string readMethod = TypeScriptTypeResolver.GetReaderMethodForPrimitive(csharpType);
        if (readMethod != "unknown")
        {
            sb.AppendLine($"{indent}const {variableName} = reader.{readMethod}();");
        }
        else
        {
            sb.AppendLine($"{indent}const {variableName} = {csharpType}.deserialize(reader);");
        }
    }
}
