name: Publish NuGet Package
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: dotnet-version: '9.0.x'

      - name: Add NuGet Source
        run: |
          dotnet nuget add source \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text \
            --name github \
            "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Pack
        run: dotnet pack --configuration Release

      - name: Push
        run: dotnet nuget push \
          **/*.nupkg \
          --source github
