name: "CI: Extensions"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ master ]
    paths:
      - "extensions/**/*.cs"
      - "extensions/**/*.csproj"
      - "extensions/**/*.sln"

  pull_request:
    branches: [ master ]
    paths:
      - "extensions/**/*.cs"
      - "extensions/**/*.csproj"
      - "extensions/**/*.sln"

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Observability
            project: extensions/Nalix.Observability.sln
          - name: Traversal
            project: extensions/Nalix.Traversal.sln
          - name: Tunneling
            project: extensions/Nalix.Tunneling.sln

    uses: ./.github/workflows/_build.yml
    with:
      os: ubuntu-latest
      project: ${{ matrix.project }}
      test: ""
      deploy: false