name: "CI: Linux Build & Test"
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"
      - "tests/**"
      - "*.sln"
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
      - "tests/**"
      - "*.sln"

permissions:
  contents: read
  checks: write
  pull-requests: write # required for test result comments

jobs:
  build:
    name: Linux
    uses: ./.github/workflows/_build.yml
    with:
      os: ubuntu-latest
      project: src/Nalix.sln
      test: tests/Nalix.Tests.sln
      deploy: false
