name: "CI: Windows Build & Test"

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"
      - "tests/**"
      - "*.sln"
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
      - "tests/**"
      - "*.sln"

permissions:
  contents: read
  checks: write
  pull-requests: write # required for test result comments

jobs:
  build:
    name: Windows
    uses: ./.github/workflows/_build.yml
    with:
      os: windows-latest
      project: src/Nalix.sln
      test: tests/Nalix.Tests.sln
      deploy: false
