name: "CI: Windows Build & Test"

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"
      - "tests/**"
      - "*.sln"
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
      - "tests/**"
      - "*.sln"

permissions:
  contents: read
  checks: write
  pull-requests: write # required for test result comments

jobs:
  build:
    name: Windows
    uses: ./.github/workflows/_build.yml
    with:
      os: windows-latest
      project: |
        src/Nalix.SDK/Nalix.SDK.csproj
        src/Nalix.Common/Nalix.Common.csproj
        src/Nalix.Logging/Nalix.Logging.csproj
        src/Nalix.Network/Nalix.Network.csproj
        src/Nalix.Framework/Nalix.Framework.csproj
      test: tests/Nalix.Tests.sln
      deploy: false
