<Project Sdk="Microsoft.NET.Sdk" TreatAsLocalProperty="PublishAot">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsRoslynComponent>true</IsRoslynComponent>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>Nalix.Analyzers.CodeFixes</AssemblyName>
		<Description>Roslyn code fixes for Nalix analyzers.</Description>
		<PublishAot>false</PublishAot>
		<PublishTrimmed>false</PublishTrimmed>
		<IsTrimmable>false</IsTrimmable>
		<IsAotCompatible>false</IsAotCompatible>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Nalix.Analyzers\Nalix.Analyzers.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Composition.Runtime" Version="10.0.7" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0" PrivateAssets="all" />
		<PackageReference Include="System.Composition.AttributedModel" Version="10.0.7" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.3.0" PrivateAssets="all" />
	</ItemGroup>
</Project>
